// Verification that proves the path rather than the port (issue #592).
//
// TestConnection has always reported one boolean. That is not enough to
// guide anybody, because the four things that can go wrong are four
// different problems with four different fixes, and "could not connect
// and list the remote path" makes the two commonest of them
// indistinguishable. An operator whose key is simply not in the remote
// authorized_keys and an operator whose account cannot read the folder
// see the same red sentence, which is how somebody ends up regenerating a
// keypair to fix a chmod.
//
// The cases below are the four stages failing one at a time. Each one
// asserts the stage that failed, and, just as hard, that the stages after
// it were NOT attempted: a wizard that reported "authentication failed"
// under a green "listed the folder" would be worse than the boolean it
// replaced.
//
// The SSH server here is a real one, in-process, with a host key
// generated for the test. It is what makes stages 1 and 2 measured rather
// than inferred: an unreachable port and a host key that does not match
// are genuinely different events on the wire, and a test that stubbed the
// far side would only prove the staging code calls itself in order. The
// last two stages ride the real transport interface, so they are driven
// through a transport whose failure category is chosen by the test, which
// is the same interface the rclone adapter satisfies.
//
// Every key here is generated by the test that uses it and authorises
// access to nothing.
package service

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"errors"
	"net"
	"os"
	"path/filepath"
	"sort"
	"testing"

	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/knownhosts"

	"github.com/spdrman/rclone-manager/core/internal/config"
	"github.com/spdrman/rclone-manager/core/internal/transport"
)

// startTestSSHServer runs a real SSH server on a loopback port that
// completes a key exchange and then refuses every authentication attempt.
//
// Refusing auth is the point: this fixture exists to make stages 1 and 2
// real, and both of those complete before the first authentication packet
// is ever sent. Nothing here ever needs a private key from the client,
// which is also why verification can measure the host-key stage without
// this process reading key material.
func startTestSSHServer(t *testing.T) (host string, port int, knownHostsLine string) {
	t.Helper()
	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generating a throwaway host key: %v", err)
	}
	signer, err := ssh.NewSignerFromKey(priv)
	if err != nil {
		t.Fatalf("NewSignerFromKey: %v", err)
	}
	cfg := &ssh.ServerConfig{
		PublicKeyCallback: func(ssh.ConnMetadata, ssh.PublicKey) (*ssh.Permissions, error) {
			return nil, errors.New("this fixture authorises nothing")
		},
	}
	cfg.AddHostKey(signer)

	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("Listen: %v", err)
	}
	t.Cleanup(func() { _ = ln.Close() })
	go func() {
		for {
			conn, err := ln.Accept()
			if err != nil {
				return
			}
			go func() {
				defer func() { _ = conn.Close() }()
				serverConn, chans, reqs, err := ssh.NewServerConn(conn, cfg)
				if err != nil {
					return
				}
				go ssh.DiscardRequests(reqs)
				for ch := range chans {
					_ = ch.Reject(ssh.Prohibited, "this fixture opens no channels")
				}
				_ = serverConn.Close()
			}()
		}
	}()

	addr := ln.Addr().(*net.TCPAddr)
	return addr.IP.String(), addr.Port, knownhosts.Line([]string{net.JoinHostPort(addr.IP.String(), itoaPort(addr.Port))}, signer.PublicKey())
}

func itoaPort(p int) string {
	const digits = "0123456789"
	if p == 0 {
		return "0"
	}
	var buf [8]byte
	i := len(buf)
	for p > 0 {
		i--
		buf[i] = digits[p%10]
		p /= 10
	}
	return string(buf[i:])
}

// stagedTransport is a transport.Transport whose List fails with a
// category the test chooses, and which records whether it was called at
// all. That second half is what proves the earlier stages STOP: a
// verification that failed the host key and still opened an sftp session
// would be reporting a refusal it did not act on.
type stagedTransport struct {
	err    error
	called bool
}

func (s *stagedTransport) List(context.Context, transport.Source) ([]transport.RemoteArtifact, error) {
	s.called = true
	return nil, s.err
}

func (s *stagedTransport) Stat(context.Context, transport.Source, string) (transport.RemoteArtifact, error) {
	return transport.RemoteArtifact{}, s.err
}

func (s *stagedTransport) CopyToLocal(context.Context, transport.Source, string, string) (transport.TransferResult, error) {
	return transport.TransferResult{}, s.err
}

func (s *stagedTransport) RemoteHash(context.Context, transport.Source, string, transport.HashAlgorithm) (string, error) {
	return "", s.err
}

func (s *stagedTransport) DeleteRemote(context.Context, transport.Source, string) error { return s.err }

var _ transport.Transport = (*stagedTransport)(nil)

// stageStatuses flattens a result into "name=status" pairs so a case can
// assert the whole shape of a verification in one comparison rather than
// four lookups that each pass while the shape is wrong.
func stageStatuses(res ConnectionTestResult) []string {
	var out []string
	for _, s := range res.Stages {
		out = append(out, s.Name+"="+s.Status)
	}
	return out
}

func stageNamed(t *testing.T, res ConnectionTestResult, name string) ConnectionTestStage {
	t.Helper()
	for _, s := range res.Stages {
		if s.Name == name {
			return s
		}
	}
	t.Fatalf("no %q stage in %v", name, stageStatuses(res))
	return ConnectionTestStage{}
}

func requireStages(t *testing.T, res ConnectionTestResult, want ...string) {
	t.Helper()
	got := stageStatuses(res)
	if len(got) != len(want) {
		t.Fatalf("stages = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("stages = %v, want %v", got, want)
		}
	}
}

// importedTestKey puts a real key in the store and returns its id, so a
// verification has something to name.
func importedTestKey(t *testing.T, configPath string) string {
	t.Helper()
	pem, _, _ := throwawayKeyPair(t)
	ref, err := importSSHKeyInto(configPath, pem, "")
	if err != nil {
		t.Fatalf("importSSHKeyInto: %v", err)
	}
	return ref.ID
}

// TestTestConnection_UnreachableHostFailsAtConnectAndAttemptsNothingElse
// is the first stage on its own.
//
// A closed port is the one failure an operator can diagnose without any
// help, and it is also the one that must not be reported as an
// authentication problem. Nothing after it is attempted, and the
// transport is never opened.
func TestTestConnection_UnreachableHostFailsAtConnectAndAttemptsNothingElse(t *testing.T) {
	configPath := writeTestConfigFile(t)
	keyID := importedTestKey(t, configPath)

	// A port nothing is listening on: bind one, learn its number, then
	// close it. Picking a constant would be picking a fight with whatever
	// else is running on this machine.
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("Listen: %v", err)
	}
	closedPort := ln.Addr().(*net.TCPAddr).Port
	_ = ln.Close()

	tr := &stagedTransport{}
	res, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, ConnectionTestRequest{
		Host:           "127.0.0.1",
		Port:           closedPort,
		User:           "backup-agent",
		SSHKeyID:       keyID,
		KnownHostsLine: "127.0.0.1 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExampleNotARealKey",
		RemotePath:     "/var/backups",
	})
	if err != nil {
		t.Fatalf("testConnectionVia: %v", err)
	}
	if res.OK {
		t.Fatal("a verification against a closed port reported OK")
	}
	requireStages(t, res,
		"connect=failed",
		"host_key=skipped",
		"authenticate=skipped",
		"list=skipped",
	)
	if tr.called {
		t.Error("the transport was opened after the connect stage had already failed")
	}
}

// TestTestConnection_HostKeyMismatchStopsBeforeAuthentication is the
// stage the whole trust model hangs off.
//
// It fails against a real server offering a real host key that is not the
// one pinned, which is precisely what a machine in the middle looks like,
// and it stops there. Reporting an authentication result past a host key
// that did not match would mean this process had authenticated to
// something it could not identify.
func TestTestConnection_HostKeyMismatchStopsBeforeAuthentication(t *testing.T) {
	configPath := writeTestConfigFile(t)
	keyID := importedTestKey(t, configPath)
	host, port, _ := startTestSSHServer(t)

	// A syntactically valid line for the right address pinning a
	// different key: a second throwaway server's host key.
	_, _, otherLine := startTestSSHServer(t)
	otherKey := hostKeyOfLine(t, otherLine)
	mismatched := knownhosts.Line([]string{net.JoinHostPort(host, itoaPort(port))}, otherKey)

	tr := &stagedTransport{}
	res, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, ConnectionTestRequest{
		Host:           host,
		Port:           port,
		User:           "backup-agent",
		SSHKeyID:       keyID,
		KnownHostsLine: mismatched,
		RemotePath:     "/var/backups",
	})
	if err != nil {
		t.Fatalf("testConnectionVia: %v", err)
	}
	requireStages(t, res,
		"connect=passed",
		"host_key=failed",
		"authenticate=skipped",
		"list=skipped",
	)
	if tr.called {
		t.Error("an sftp session was opened against a host whose key did not match what this set trusts")
	}

	detail := stageNamed(t, res, "host_key").Detail
	if detail == "" {
		t.Fatal("the host key stage failed with no detail; the two fingerprints are the entire content of the decision")
	}
	if !containsFingerprint(detail) {
		t.Errorf("the host key refusal %q names no SHA256 fingerprint, so there is nothing for an operator to compare against the server itself", detail)
	}
}

// TestTestConnection_SeparatesAuthenticationFromListing is the split the
// issue is really about.
//
// Two failures, identical under the old boolean and completely different
// in what they ask an operator to do. Authentication failing means the
// public half is not in the remote authorized_keys. Listing failing with
// authentication green means the account works and cannot read the
// folder, which is a permissions problem on the source and nothing to do
// with keys.
func TestTestConnection_SeparatesAuthenticationFromListing(t *testing.T) {
	configPath := writeTestConfigFile(t)
	keyID := importedTestKey(t, configPath)
	host, port, line := startTestSSHServer(t)

	req := ConnectionTestRequest{
		Host:           host,
		Port:           port,
		User:           "backup-agent",
		SSHKeyID:       keyID,
		KnownHostsLine: line,
		RemotePath:     "/var/backups",
	}

	t.Run("the key is not authorised", func(t *testing.T) {
		tr := &stagedTransport{err: transport.NewError(transport.Authentication, "list", errors.New("ssh: unable to authenticate"))}
		res, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, req)
		if err != nil {
			t.Fatalf("testConnectionVia: %v", err)
		}
		requireStages(t, res,
			"connect=passed",
			"host_key=passed",
			"authenticate=failed",
			"list=skipped",
		)
	})

	t.Run("the account cannot read the folder", func(t *testing.T) {
		tr := &stagedTransport{err: transport.NewError(transport.PermissionDenied, "list", errors.New("permission denied"))}
		res, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, req)
		if err != nil {
			t.Fatalf("testConnectionVia: %v", err)
		}
		requireStages(t, res,
			"connect=passed",
			"host_key=passed",
			"authenticate=passed",
			"list=failed",
		)
		if res.OK {
			t.Error("a verification whose listing failed reported OK")
		}
	})

	t.Run("everything works", func(t *testing.T) {
		tr := &stagedTransport{}
		res, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, req)
		if err != nil {
			t.Fatalf("testConnectionVia: %v", err)
		}
		requireStages(t, res,
			"connect=passed",
			"host_key=passed",
			"authenticate=passed",
			"list=passed",
		)
		if !res.OK {
			t.Errorf("all four stages passed and OK is false, message %q", res.Message)
		}
		if res.Message != "" {
			t.Errorf("Message = %q on a passing verification, want empty: #211's callers read OK and only render Message when OK is false", res.Message)
		}
	})
}

// TestTestConnection_KeepsTheOldBooleanExactlyAsItWas is the
// compatibility half.
//
// #211's existing callers read ok and message and nothing else, so
// growing this response must not change either of them for any outcome
// they already see.
func TestTestConnection_KeepsTheOldBooleanExactlyAsItWas(t *testing.T) {
	configPath := writeTestConfigFile(t)
	keyID := importedTestKey(t, configPath)
	host, port, line := startTestSSHServer(t)

	tr := &stagedTransport{err: transport.NewError(transport.Authentication, "list", errors.New("ssh: unable to authenticate"))}
	res, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, ConnectionTestRequest{
		Host: host, Port: port, User: "backup-agent", SSHKeyID: keyID, KnownHostsLine: line, RemotePath: "/var/backups",
	})
	if err != nil {
		t.Fatalf("testConnectionVia: %v", err)
	}
	if res.OK {
		t.Error("OK is true for a failed verification")
	}
	if res.Message == "" {
		t.Error("Message is empty for a failed verification; every caller before this change renders it as the whole reason")
	}
}

// TestVerificationNeverWritesATrustAnchor is the promise the wizard makes
// on every pane: nothing is persisted until Apply.
//
// A verification writes the candidate known_hosts line to a temporary
// file for the duration of one check. It must not touch the set's own
// anchor, and the directory those live in must not gain a file, because
// prepareTrustChange refuses on the acknowledgement BEFORE it stages
// anything and a verification that staged one first would have moved the
// refusal.
func TestVerificationNeverWritesATrustAnchor(t *testing.T) {
	configPath := writeTestConfigFile(t)
	keyID := importedTestKey(t, configPath)
	host, port, line := startTestSSHServer(t)

	trustDir := filepath.Join(filepath.Dir(configPath), "known_hosts.d")
	before := dirListing(t, trustDir)

	tr := &stagedTransport{}
	if _, err := testConnectionVia(context.Background(), tr, configPath, config.KeyEncryption{}, ConnectionTestRequest{
		Host: host, Port: port, User: "backup-agent", SSHKeyID: keyID, KnownHostsLine: line, RemotePath: "/var/backups",
	}); err != nil {
		t.Fatalf("testConnectionVia: %v", err)
	}

	if after := dirListing(t, trustDir); !equalStrings(before, after) {
		t.Errorf("known_hosts.d went from %v to %v across a verification. Verifying settles nothing; only the acknowledged patch does", before, after)
	}
}

// hostKeyOfLine pulls the public key out of a known_hosts line, so a case
// can build a DIFFERENT line for the same address out of a real key
// rather than out of an invented string. A mismatch built from something
// that does not parse would fail earlier, for the wrong reason.
func hostKeyOfLine(t *testing.T, line string) ssh.PublicKey {
	t.Helper()
	entry, err := parseKnownHostsLine(line)
	if err != nil {
		t.Fatalf("parsing the fixture known_hosts line: %v", err)
	}
	return entry.Key
}

// containsFingerprint reports whether a message names at least one
// SHA256 fingerprint, in the form `ssh-keygen -lf` prints.
func containsFingerprint(s string) bool {
	for i := 0; i+7 <= len(s); i++ {
		if s[i:i+7] == "SHA256:" {
			return true
		}
	}
	return false
}

// dirListing is every name in dir, or nil when it does not exist. Absent
// and empty are the same answer here on purpose: the assertion is that a
// verification changed nothing, and a directory that did not exist before
// and does not exist after has not changed.
func dirListing(t *testing.T, dir string) []string {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var out []string
	for _, e := range entries {
		out = append(out, e.Name())
	}
	sort.Strings(out)
	return out
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
