// The listing this product never had (issue #592).
//
// Every case here is about the same defect from a different side: an
// imported key's id is shown once, in the response to the POST that
// created it, and after that nothing in this product can name it. So the
// wizard's "use a managed key" radio refuses at save, the edit box asks an
// operator to paste a uuid they were shown months ago, and the key the
// installer generated and mounted is unreachable from the only surface
// that could offer it.
//
// The three groups fail differently on purpose.
//
// The store cases prove a listing exists AND that it stays inside
// SSHKeyRef's rule: ids, algorithms, fingerprints and which sets use a
// key, never a server-side path and never key material. That second half
// is asserted over the whole returned value rather than field by field,
// because a field added later is exactly how a path gets back onto the
// wire.
//
// The discovery cases prove the scan describes candidates without reading
// them. The sharp one is a real, perfectly parseable private key with no
// .pub beside it: an implementation that read the private key to fill the
// fingerprint column would pass every other case here and fail that one.
//
// The location cases prove an empty result says where it looked. "No keys
// found" and "I looked in these three places and found nothing" are the
// same list and completely different sentences, and the epic's refusals
// rule is that an operator gets the second one.
//
// Every key in this file is generated by the test that uses it and
// authorises access to nothing.
package service

import (
	"context"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	"golang.org/x/crypto/ssh"
)

// throwawayKeyPair generates a fresh ed25519 keypair and returns the
// OpenSSH private PEM, the authorized_keys-shaped public line, and the
// SHA256 fingerprint both halves share. Fresh per call, so no two cases
// can accidentally share an identity, and never a credential: no server
// anywhere trusts these.
func throwawayKeyPair(t *testing.T) (privatePEM []byte, publicLine string, fingerprint string) {
	t.Helper()
	pub, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generating a throwaway ed25519 key: %v", err)
	}
	block, err := ssh.MarshalPrivateKey(priv, "backupd test fixture")
	if err != nil {
		t.Fatalf("marshalling the throwaway private key: %v", err)
	}
	sshPub, err := ssh.NewPublicKey(pub)
	if err != nil {
		t.Fatalf("deriving the public half: %v", err)
	}
	return pemEncode(t, block), strings.TrimSpace(string(ssh.MarshalAuthorizedKey(sshPub))), ssh.FingerprintSHA256(sshPub)
}

// pemEncode renders one PEM block, so a generated fixture reaches disk in
// the same shape ssh-keygen would have written it.
func pemEncode(t *testing.T, block *pem.Block) []byte {
	t.Helper()
	return pem.EncodeToMemory(block)
}

// everyStringIn walks v and collects every string it holds, at any depth.
// The no-paths and no-material assertions below are written against this
// rather than against a list of field names, so a field added to a
// listing type later is covered by them the day it is added.
func everyStringIn(v reflect.Value, out *[]string) {
	switch v.Kind() {
	case reflect.String:
		*out = append(*out, v.String())
	case reflect.Slice, reflect.Array:
		for i := 0; i < v.Len(); i++ {
			everyStringIn(v.Index(i), out)
		}
	case reflect.Struct:
		for i := 0; i < v.NumField(); i++ {
			everyStringIn(v.Field(i), out)
		}
	case reflect.Pointer, reflect.Interface:
		if !v.IsNil() {
			everyStringIn(v.Elem(), out)
		}
	}
}

func stringsIn(value any) []string {
	var out []string
	everyStringIn(reflect.ValueOf(value), &out)
	return out
}

// TestListSSHKeys_NamesEveryImportedKey is the foundation case: after two
// imports, the store can be listed, and each row carries the id the
// importer returned beside the algorithm and fingerprint an operator
// compares by eye.
//
// Without this there is no wizard to build. `--ssh-key-id` and the edit
// box both take an id, and until this method exists there is no way to
// learn one that does not involve having written it down at import time.
func TestListSSHKeys_NamesEveryImportedKey(t *testing.T) {
	svc, _ := openTestService(t)
	ctx := context.Background()

	firstPEM, _, firstFingerprint := throwawayKeyPair(t)
	secondPEM, _, secondFingerprint := throwawayKeyPair(t)

	first, err := svc.ImportSSHKey(ctx, firstPEM, "")
	if err != nil {
		t.Fatalf("ImportSSHKey (first): %v", err)
	}
	second, err := svc.ImportSSHKey(ctx, secondPEM, "")
	if err != nil {
		t.Fatalf("ImportSSHKey (second): %v", err)
	}

	listed, err := svc.ListSSHKeys(ctx)
	if err != nil {
		t.Fatalf("ListSSHKeys: %v", err)
	}
	if len(listed) != 2 {
		t.Fatalf("ListSSHKeys returned %d keys, want the 2 that were imported", len(listed))
	}

	byID := map[string]SSHKeyListing{}
	for _, k := range listed {
		byID[k.ID] = k
	}
	for _, want := range []struct {
		id          string
		fingerprint string
	}{{first.ID, firstFingerprint}, {second.ID, secondFingerprint}} {
		got, ok := byID[want.id]
		if !ok {
			t.Fatalf("the key imported as %q is not in the listing; the id the importer returned is the only handle a caller ever has", want.id)
		}
		if got.Fingerprint != want.fingerprint {
			t.Errorf("key %q has fingerprint %q, want %q (the one `ssh-keygen -lf` prints for the same key)", want.id, got.Fingerprint, want.fingerprint)
		}
		if got.Algorithm != "ssh-ed25519" {
			t.Errorf("key %q has algorithm %q, want %q", want.id, got.Algorithm, "ssh-ed25519")
		}
		if got.ImportedAt.IsZero() {
			t.Errorf("key %q has no imported-at time; the wizard's list orders and describes rows by it", want.id)
		}
	}
}

// TestListSSHKeys_CarriesNoPathAndNoKeyMaterial holds the listing to the
// rule SSHKeyRef's own doc already makes for the import response.
//
// The listing is a new way for the key store to reach a browser, and it
// is the one shaped like an inventory, so it is the one where a path
// column looks helpful. It is not: a path tells an API caller this
// process's filesystem layout and tells an operator nothing they can act
// on, because the file it names is inside a container they do not have a
// shell in.
func TestListSSHKeys_CarriesNoPathAndNoKeyMaterial(t *testing.T) {
	svc, configPath := openTestService(t)
	ctx := context.Background()

	pem, publicLine, _ := throwawayKeyPair(t)
	if _, err := svc.ImportSSHKey(ctx, pem, ""); err != nil {
		t.Fatalf("ImportSSHKey: %v", err)
	}

	listed, err := svc.ListSSHKeys(ctx)
	if err != nil {
		t.Fatalf("ListSSHKeys: %v", err)
	}

	keysDir := filepath.Join(filepath.Dir(configPath), "ssh_keys")
	for _, s := range stringsIn(listed) {
		if strings.Contains(s, keysDir) || strings.Contains(s, filepath.Dir(configPath)) {
			t.Errorf("a listing field carries the server-side path %q; SSHKeyRef.KeyFile is kept off the wire so a caller never learns this process's filesystem layout, and a listing is not an exception", s)
		}
		if strings.Contains(s, "PRIVATE KEY") {
			t.Errorf("a listing field carries private key material: %q", s)
		}
	}

	// The PUBLIC half is the one thing here that may travel, and it has
	// to: a failed authentication check is fixed by pasting exactly this
	// line into the remote authorized_keys, and an operator who cannot
	// see it has nothing to paste.
	if len(listed) != 1 {
		t.Fatalf("ListSSHKeys returned %d keys, want 1", len(listed))
	}
	if listed[0].PublicKey != publicLine {
		t.Errorf("PublicKey = %q, want the authorized_keys line %q", listed[0].PublicKey, publicLine)
	}
}

// TestListSSHKeys_NamesTheBackupSetsUsingEachKey is the column that turns
// a wall of uuids into a decision.
//
// An operator choosing between three identical-looking rows is choosing
// on this and nothing else. It is also what makes replacing a key
// something anybody can reason about: a key four sets depend on and a key
// nothing references are very different things to point a fifth set at.
func TestListSSHKeys_NamesTheBackupSetsUsingEachKey(t *testing.T) {
	svc, _ := openTestService(t)
	ctx := context.Background()

	shared := validCreateReq(t, svc, "uses-the-shared-key")
	if _, err := svc.CreateBackupSet(ctx, shared); err != nil {
		t.Fatalf("CreateBackupSet (first): %v", err)
	}
	second := validCreateReq(t, svc, "also-uses-the-shared-key")
	second.SSHKeyID = shared.SSHKeyID
	if _, err := svc.CreateBackupSet(ctx, second); err != nil {
		t.Fatalf("CreateBackupSet (second): %v", err)
	}

	// A third key imported and referenced by nothing, so "used by
	// nothing" is proven to be a real answer rather than an empty list
	// this test never produced.
	unusedPEM, _, _ := throwawayKeyPair(t)
	unused, err := svc.ImportSSHKey(ctx, unusedPEM, "")
	if err != nil {
		t.Fatalf("ImportSSHKey (unused): %v", err)
	}

	listed, err := svc.ListSSHKeys(ctx)
	if err != nil {
		t.Fatalf("ListSSHKeys: %v", err)
	}
	for _, k := range listed {
		switch k.ID {
		case shared.SSHKeyID:
			want := []string{"api/also-uses-the-shared-key", "api/uses-the-shared-key"}
			if !reflect.DeepEqual(k.UsedBy, want) {
				t.Errorf("the shared key reports UsedBy %v, want %v", k.UsedBy, want)
			}
		case unused.ID:
			if len(k.UsedBy) != 0 {
				t.Errorf("a key nothing references reports UsedBy %v, want none", k.UsedBy)
			}
		}
	}
}

// TestListSSHKeys_MarksAPassphraseProtectedKey covers the row the wizard
// has to list and must not offer as ready.
//
// #269 already refuses to import a passphrase-protected key without its
// passphrase, so a key in the store that will not parse unencrypted got
// there some other way: an operator dropped it in, or a restore put it
// back. Either way it is a real key that cannot be verified until its
// passphrase resolves, and the honest listing says so rather than
// dropping the row or showing a blank fingerprint under a confident
// heading.
func TestListSSHKeys_MarksAPassphraseProtectedKey(t *testing.T) {
	svc, configPath := openTestService(t)
	ctx := context.Background()

	_, priv, err := ed25519.GenerateKey(rand.Reader)
	if err != nil {
		t.Fatalf("generating a throwaway ed25519 key: %v", err)
	}
	block, err := ssh.MarshalPrivateKeyWithPassphrase(priv, "backupd test fixture", []byte("not-a-real-passphrase"))
	if err != nil {
		t.Fatalf("marshalling an encrypted throwaway key: %v", err)
	}
	keysDir := filepath.Join(filepath.Dir(configPath), "ssh_keys")
	if err := os.MkdirAll(keysDir, 0o700); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(filepath.Join(keysDir, "encrypted-key"), pemEncode(t, block), 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	listed, err := svc.ListSSHKeys(ctx)
	if err != nil {
		t.Fatalf("ListSSHKeys: %v", err)
	}
	if len(listed) != 1 {
		t.Fatalf("ListSSHKeys returned %d keys, want the 1 in the store", len(listed))
	}
	if !listed[0].PassphraseProtected {
		t.Error("a passphrase-protected key is not marked as one; the wizard lists it and refuses to verify against it until its passphrase resolves")
	}
	if listed[0].Fingerprint != "" {
		// The public half of an OpenSSH-format encrypted key is stored in
		// the clear, so a fingerprint IS derivable. Whether it is filled
		// in is an implementation choice; what is not is that the row
		// exists and is marked.
		t.Logf("the encrypted key reports fingerprint %q, which is fine: an OpenSSH private key carries its public half unencrypted", listed[0].Fingerprint)
	}
}

// TestDiscoverSSHKeyCandidates_ReadsThePubAndNeverThePrivateKey is the
// sharp case, and the one an implementation that shortcuts will fail.
//
// Two files sit side by side. One is a real, perfectly parseable private
// key with NO .pub beside it: it must come back listed, unselectable, and
// with an EMPTY fingerprint, because filling that column would mean this
// endpoint read a private key in order to describe it in a list. The
// other has a .pub, and its fingerprint must be the .pub's.
func TestDiscoverSSHKeyCandidates_ReadsThePubAndNeverThePrivateKey(t *testing.T) {
	svc, _ := openTestService(t)
	ctx := context.Background()

	dir := t.TempDir()
	t.Setenv(sshDiscoveryDirEnv, dir)

	withPubPEM, withPubLine, withPubFingerprint := throwawayKeyPair(t)
	if err := os.WriteFile(filepath.Join(dir, "id_ed25519"), withPubPEM, 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	if err := os.WriteFile(filepath.Join(dir, "id_ed25519.pub"), []byte(withPubLine+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	lonelyPEM, _, lonelyFingerprint := throwawayKeyPair(t)
	if err := os.WriteFile(filepath.Join(dir, "id_lonely"), lonelyPEM, 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	found, err := svc.DiscoverSSHKeyCandidates(ctx)
	if err != nil {
		t.Fatalf("DiscoverSSHKeyCandidates: %v", err)
	}

	byPath := map[string]SSHKeyCandidate{}
	for _, c := range found.Candidates {
		byPath[c.Path] = c
	}

	described, ok := byPath[filepath.Join(dir, "id_ed25519")]
	if !ok {
		t.Fatalf("the key with a .pub beside it was not discovered; found %+v", found.Candidates)
	}
	if described.Fingerprint != withPubFingerprint {
		t.Errorf("fingerprint = %q, want %q read from the .pub beside it", described.Fingerprint, withPubFingerprint)
	}
	if !described.Selectable {
		t.Errorf("a key with a readable .pub is not selectable: %q", described.Reason)
	}

	lonely, ok := byPath[filepath.Join(dir, "id_lonely")]
	if !ok {
		t.Fatalf("a private key with no .pub beside it was dropped from the listing; it has to appear, marked, so an operator can see why it is not offered")
	}
	if lonely.Fingerprint != "" {
		t.Errorf("a private key with no .pub reports fingerprint %q. The only way to know that is to have read the private key, which is exactly what a listing must not do", lonely.Fingerprint)
	}
	if lonely.Fingerprint == lonelyFingerprint {
		t.Error("the reported fingerprint is the private key's own, so the private key was read to build a list")
	}
	if lonely.Selectable {
		t.Error("a candidate with no fingerprint is selectable; there is nothing to compare against the server, so it cannot be offered")
	}
	if lonely.Reason == "" {
		t.Error("an unselectable candidate carries no reason; a row an operator cannot pick and cannot explain is worse than no row")
	}
}

// TestDiscoverSSHKeyCandidates_NamesEveryLocationItSearched is the epic's
// refusals rule applied to a listing.
//
// An empty result has two readings, "you have no keys" and "I could not
// look where your keys are", and on a packaged install the second one is
// the true one: the engine is a distroless container with five mounts and
// no home directory at all. A scan that answers with a bare empty list
// tells an operator the opposite of what happened.
func TestDiscoverSSHKeyCandidates_NamesEveryLocationItSearched(t *testing.T) {
	svc, _ := openTestService(t)

	empty := t.TempDir()
	t.Setenv(sshDiscoveryDirEnv, empty)
	t.Setenv("HOME", t.TempDir())

	found, err := svc.DiscoverSSHKeyCandidates(context.Background())
	if err != nil {
		t.Fatalf("DiscoverSSHKeyCandidates: %v", err)
	}
	if len(found.Candidates) != 0 {
		t.Fatalf("expected no candidates from empty locations, got %+v", found.Candidates)
	}
	if len(found.Locations) == 0 {
		t.Fatal("the scan found nothing and reported nowhere. An empty list has to read as \"I looked in these places\", never as \"you have no keys\"")
	}

	var named []string
	for _, l := range found.Locations {
		named = append(named, l.Path)
		if l.Kind == "" {
			t.Errorf("location %q has no kind; a caller renders \"the key file the configuration names\" differently from \"a directory that is not mounted\"", l.Path)
		}
	}
	if !slicesContains(named, empty) {
		t.Errorf("the searched locations %v do not include the discovery directory %q that was actually scanned", named, empty)
	}
	// The mount point a packaged install has and a test machine does
	// not. It must still be reported, as searched and absent, because
	// "not mounted here" is the answer an operator needs.
	if !slicesContains(named, sshDiscoveryMountDir) {
		t.Errorf("the searched locations %v do not include %q. On a packaged install that is where the installer's own key is mounted, and a scan that silently skips a location it could not read is the empty-list defect wearing a different coat", named, sshDiscoveryMountDir)
	}
}

// TestImportSSHKeyCandidate_TakesAnOpaqueIDAndNeverAPath is the traversal
// case this endpoint needs before it exists.
//
// Selecting a discovered candidate reads a private key server-side and
// copies it into the store, which is the same act `--ssh-key-file`
// already performs, and the browser must not be the thing that says which
// file. So the handle is an opaque candidate id that only resolves
// against a fresh scan of the fixed locations, and anything shaped like a
// path is refused outright rather than joined onto a directory.
func TestImportSSHKeyCandidate_TakesAnOpaqueIDAndNeverAPath(t *testing.T) {
	svc, _ := openTestService(t)
	ctx := context.Background()

	dir := t.TempDir()
	t.Setenv(sshDiscoveryDirEnv, dir)
	pem, pubLine, fingerprint := throwawayKeyPair(t)
	keyPath := filepath.Join(dir, "id_ed25519")
	if err := os.WriteFile(keyPath, pem, 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
	if err := os.WriteFile(keyPath+".pub", []byte(pubLine+"\n"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	found, err := svc.DiscoverSSHKeyCandidates(ctx)
	if err != nil {
		t.Fatalf("DiscoverSSHKeyCandidates: %v", err)
	}
	var candidateID string
	for _, c := range found.Candidates {
		if c.Path == keyPath {
			candidateID = c.ID
		}
	}
	if candidateID == "" {
		t.Fatalf("the discovered key has no candidate id to select it by; found %+v", found.Candidates)
	}
	if strings.ContainsAny(candidateID, "/\\") || strings.Contains(candidateID, dir) {
		t.Errorf("the candidate id %q is path-shaped. An identifier a browser sends back has to be opaque, or this endpoint becomes a way to name a file for this process to read", candidateID)
	}

	ref, err := svc.ImportSSHKeyCandidate(ctx, candidateID)
	if err != nil {
		t.Fatalf("ImportSSHKeyCandidate: %v", err)
	}
	if ref.Fingerprint != fingerprint {
		t.Errorf("the imported key has fingerprint %q, want the candidate's %q", ref.Fingerprint, fingerprint)
	}
	if ref.ID == "" {
		t.Error("the import returned no id, so the key it just copied cannot be referenced")
	}

	// It is in the store now, and the original is left alone: the same
	// promise `--ssh-key-file` already makes.
	listed, err := svc.ListSSHKeys(ctx)
	if err != nil {
		t.Fatalf("ListSSHKeys: %v", err)
	}
	var inStore bool
	for _, k := range listed {
		if k.ID == ref.ID && k.Fingerprint == fingerprint {
			inStore = true
		}
	}
	if !inStore {
		t.Error("the selected candidate was not copied into the key store")
	}
	if _, err := os.Stat(keyPath); err != nil {
		t.Errorf("the original candidate file was disturbed: %v", err)
	}

	for _, bad := range []string{"../../etc/passwd", keyPath, "/etc/shadow", ""} {
		if _, err := svc.ImportSSHKeyCandidate(ctx, bad); err == nil {
			t.Errorf("ImportSSHKeyCandidate(%q) was accepted; a candidate id is not a path and a path must never be resolvable through this call", bad)
		}
	}
}

// slicesContains is here rather than pulled from slices so this file has
// no opinion about the toolchain's minimum version.
func slicesContains(haystack []string, needle string) bool {
	for _, s := range haystack {
		if s == needle {
			return true
		}
	}
	return false
}
