package machinegate_test

import (
	"context"
	"strings"
	"testing"

	"github.com/spdrman/rclone-manager/core/internal/transport/rclone"
	"github.com/spdrman/rclone-manager/core/tests/machines"
)

// TestSFTPHostKeyVerification is FR-6's host-key posture, held against real
// servers: the recorded key works, an address known_hosts has never seen is
// refused, and the same address answering with a different key is refused.
//
// Until #450 this built an alpine image with a client key baked into
// authorized_keys and started a container per subtest, inside the test
// function, because "a server whose host key can be substituted" was
// something only a rebuild could produce. It is two machines now. The
// substance is unchanged and the mechanism is the harness's.
func TestSFTPHostKeyVerification(t *testing.T) {
	m := machines.Start(t)
	src := m.Source(t)
	adapter := rclone.New()
	ctx := context.Background()

	good := src.TransportSource("sftp-hostkey", "")

	// Positive control: prove the machines themselves are sound before
	// trusting any refusal below. If this fails, the "attacks" prove
	// nothing, since they could just as well be failing for an unrelated
	// reason (wrong port, wrong user, key mismatch, sshd misconfigured).
	t.Run("recorded host key with the configured SSH key succeeds", func(t *testing.T) {
		if _, err := adapter.List(ctx, good); err != nil {
			t.Fatalf("List against the recorded host key should have succeeded, got: %v\nthe machine's own connection table:\n%s", err, src.ConnectionTable(t))
		}
	})

	t.Run("unknown host key is refused", func(t *testing.T) {
		// A second, independent machine: a live server at an address the
		// first machine's known_hosts has no entry for at all.
		other := m.AnotherSource(t)
		unknown := other.TransportSource("sftp-hostkey-unknown", "")
		unknown.KnownHosts = src.KnownHostsFile

		_, err := adapter.List(ctx, unknown)
		if err == nil {
			t.Fatal("List against a host with no known_hosts entry should have been refused, it succeeded")
		}
		if !strings.Contains(err.Error(), "knownhosts: key is unknown") {
			t.Fatalf("expected an unknown-host-key error, got: %v", err)
		}
	})

	t.Run("changed host key is refused (MITM)", func(t *testing.T) {
		// The same host:port the control just succeeded against, with a
		// different key pinned for it: exactly the shape of a MITM, or a
		// server quietly replaced. The decoy is generated by the harness
		// and pinned for this machine's own address, which is what makes
		// this a mismatch rather than an absence, and the subtest above is
		// what keeps the two apart.
		mitm := good
		mitm.KnownHosts = src.BadKnownHostsFile

		_, err := adapter.List(ctx, mitm)
		if err == nil {
			t.Fatal("List against a changed host key should have been refused, it succeeded")
		}
		if !strings.Contains(err.Error(), "knownhosts: key mismatch") {
			t.Fatalf("expected a host-key-mismatch error, got: %v", err)
		}
	})
}
