// Code generated by scripts/api/gen-bindings.go from api/v1/openapi.json. DO NOT EDIT.
//
// Package apicontract is the Go half of the generated /api/v1 bindings
// (issue #166). The contract document, not this file and not the handlers
// in apps/common/webhost, is the definition of the boundary: edit
// api/v1/openapi.json and re-run scripts/api/generate.sh.
//
// A hand edit here is caught by scripts/api/check-contract-drift.sh, which
// regenerates into a temporary directory and compares. A handler whose
// shape stops matching one of these types is caught by
// apps/common/webhost's TestContract_HandlerShapesMatchTheContract.
package apicontract

// Version and BasePath are the versioned boundary itself.
const (
	Version  = "v1"
	BasePath = "/api/v1"
)

// ContractSHA256 is the digest of the contract document these bindings were
// generated from.
//
// It exists so the ordinary go test run catches the commonest
// mistake, editing the contract and forgetting to regenerate, without
// shelling out to the generator: TestContract_TheBindingsWereGeneratedFromThisContract
// hashes api/v1/openapi.json and compares. The full byte-for-byte
// comparison still lives in scripts/api/check-contract-drift.sh, which is
// the only thing that can also catch a hand edit to the body of this file.
const ContractSHA256 = "bc3cf7e50ad1f25d66e7454c2ef6dbafded3c5c8dc849cf1c8dd27e8bbb6f481"

// ErrorCode is a stable, machine-readable failure token. The human-readable
// message beside it on the wire MAY change without notice; this may not.
type ErrorCode string

// The complete error-code registry. Codes are declared in the contract, not
// here, and ui/shared reads the same registry through the TypeScript half of
// these bindings, so the two can never hold different lists.
const (
	ErrorCodeAuthenticationFailed          ErrorCode = "authentication-failed"
	ErrorCodeSSHHostKeyChanged             ErrorCode = "ssh-host-key-changed"
	ErrorCodePermissionDenied              ErrorCode = "permission-denied"
	ErrorCodeRemotePathMissing             ErrorCode = "remote-path-missing"
	ErrorCodeChecksumMismatch              ErrorCode = "checksum-mismatch"
	ErrorCodeBackupStale                   ErrorCode = "backup-stale"
	ErrorCodeStorageCritical               ErrorCode = "storage-critical"
	ErrorCodeVersionMismatch               ErrorCode = "version-mismatch"
	ErrorCodeOperationConflict             ErrorCode = "operation-conflict"
	ErrorCodeUnknown                       ErrorCode = "unknown"
	ErrorCodeUnauthenticated               ErrorCode = "UNAUTHENTICATED"
	ErrorCodeRateLimited                   ErrorCode = "RATE_LIMITED"
	ErrorCodeInvalidRequest                ErrorCode = "INVALID_REQUEST"
	ErrorCodeEnrollmentClosed              ErrorCode = "ENROLLMENT_CLOSED"
	ErrorCodeBootstrapTokenInvalid         ErrorCode = "BOOTSTRAP_TOKEN_INVALID"
	ErrorCodeInternalError                 ErrorCode = "INTERNAL_ERROR"
	ErrorCodeCSRFTokenMissing              ErrorCode = "CSRF_TOKEN_MISSING"
	ErrorCodeCSRFTokenMismatch             ErrorCode = "CSRF_TOKEN_MISMATCH"
	ErrorCodeRetentionPlanStale            ErrorCode = "RETENTION_PLAN_STALE"
	ErrorCodeRetentionPlanNotFound         ErrorCode = "RETENTION_PLAN_NOT_FOUND"
	ErrorCodeRetentionApplyBusy            ErrorCode = "RETENTION_APPLY_BUSY"
	ErrorCodeBackupSetNotFound             ErrorCode = "BACKUP_SET_NOT_FOUND"
	ErrorCodeOperationNotFound             ErrorCode = "OPERATION_NOT_FOUND"
	ErrorCodeOperationAlreadyRunning       ErrorCode = "OPERATION_ALREADY_RUNNING"
	ErrorCodeIdempotencyKeyConflict        ErrorCode = "IDEMPOTENCY_KEY_CONFLICT"
	ErrorCodeConfigRevisionStale           ErrorCode = "CONFIG_REVISION_STALE"
	ErrorCodeSSHKeyNotFound                ErrorCode = "SSH_KEY_NOT_FOUND"
	ErrorCodeHostKeyProbeFailed            ErrorCode = "HOST_KEY_PROBE_FAILED"
	ErrorCodeDestructiveOperationsDisabled ErrorCode = "DESTRUCTIVE_OPERATIONS_DISABLED"
	ErrorCodeInternal                      ErrorCode = "INTERNAL"
)

// WireErrorCodes is codes a server may put on the wire. Every one of these is emitted by real handler code, and apps/common/webhost's TestContract_EveryWireErrorCodeIsRegistered holds that both ways.
var WireErrorCodes = []ErrorCode{
	ErrorCodeUnauthenticated,
	ErrorCodeRateLimited,
	ErrorCodeInvalidRequest,
	ErrorCodeEnrollmentClosed,
	ErrorCodeBootstrapTokenInvalid,
	ErrorCodeInternalError,
	ErrorCodeCSRFTokenMissing,
	ErrorCodeCSRFTokenMismatch,
	ErrorCodeRetentionPlanStale,
	ErrorCodeRetentionPlanNotFound,
	ErrorCodeRetentionApplyBusy,
	ErrorCodeBackupSetNotFound,
	ErrorCodeOperationNotFound,
	ErrorCodeOperationAlreadyRunning,
	ErrorCodeIdempotencyKeyConflict,
	ErrorCodeConfigRevisionStale,
	ErrorCodeSSHKeyNotFound,
	ErrorCodeHostKeyProbeFailed,
	ErrorCodeDestructiveOperationsDisabled,
	ErrorCodeInternal,
}

// UIErrorCodes is the shared UI's own presentation vocabulary. No endpoint emits these; they are registered here so there is one registry rather than a second hand-maintained list in ui/shared.
var UIErrorCodes = []ErrorCode{
	ErrorCodeAuthenticationFailed,
	ErrorCodeSSHHostKeyChanged,
	ErrorCodePermissionDenied,
	ErrorCodeRemotePathMissing,
	ErrorCodeChecksumMismatch,
	ErrorCodeBackupStale,
	ErrorCodeStorageCritical,
	ErrorCodeVersionMismatch,
	ErrorCodeOperationConflict,
	ErrorCodeUnknown,
}

// ErrorCodes is every registered code, wire and UI alike, in contract order.
var ErrorCodes = []ErrorCode{
	ErrorCodeAuthenticationFailed,
	ErrorCodeSSHHostKeyChanged,
	ErrorCodePermissionDenied,
	ErrorCodeRemotePathMissing,
	ErrorCodeChecksumMismatch,
	ErrorCodeBackupStale,
	ErrorCodeStorageCritical,
	ErrorCodeVersionMismatch,
	ErrorCodeOperationConflict,
	ErrorCodeUnknown,
	ErrorCodeUnauthenticated,
	ErrorCodeRateLimited,
	ErrorCodeInvalidRequest,
	ErrorCodeEnrollmentClosed,
	ErrorCodeBootstrapTokenInvalid,
	ErrorCodeInternalError,
	ErrorCodeCSRFTokenMissing,
	ErrorCodeCSRFTokenMismatch,
	ErrorCodeRetentionPlanStale,
	ErrorCodeRetentionPlanNotFound,
	ErrorCodeRetentionApplyBusy,
	ErrorCodeBackupSetNotFound,
	ErrorCodeOperationNotFound,
	ErrorCodeOperationAlreadyRunning,
	ErrorCodeIdempotencyKeyConflict,
	ErrorCodeConfigRevisionStale,
	ErrorCodeSSHKeyNotFound,
	ErrorCodeHostKeyProbeFailed,
	ErrorCodeDestructiveOperationsDisabled,
	ErrorCodeInternal,
}

// ErrorClasses groups codes by the refusal they represent, so a caller (or
// a red team) can assert the RIGHT refusal rather than any refusal.
var ErrorClasses = map[string][]ErrorCode{
	"authentication": {ErrorCodeUnauthenticated, ErrorCodeBootstrapTokenInvalid},
	"authorization":  {ErrorCodeEnrollmentClosed, ErrorCodeDestructiveOperationsDisabled, ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
	"conflict":       {ErrorCodeRetentionPlanStale, ErrorCodeRetentionApplyBusy, ErrorCodeOperationAlreadyRunning, ErrorCodeIdempotencyKeyConflict, ErrorCodeConfigRevisionStale},
	"internal":       {ErrorCodeInternal, ErrorCodeInternalError},
	"not-found":      {ErrorCodeBackupSetNotFound, ErrorCodeOperationNotFound, ErrorCodeRetentionPlanNotFound},
	"throttling":     {ErrorCodeRateLimited},
	"validation":     {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound, ErrorCodeHostKeyProbeFailed},
}

// Endpoint is one operation of the contract, with the requirements a
// handler has to satisfy expressed as data rather than as convention:
// whether a session is required, whether CSRF is required, whether an
// idempotency key is required, whether the destructive gate stands in
// front of it, and which optimistic-concurrency token it reads.
type Endpoint struct {
	ID              string
	Method          string
	Path            string
	Authenticated   bool
	CSRFRequired    bool
	IdempotencyKey  string
	DestructiveGate bool
	Concurrency     string
	RequestSchema   string
	ResponseSchema  string
	SuccessStatus   int
	ErrorCodes      map[int][]ErrorCode
}

// Endpoints is every operation the contract declares, ordered by path then
// method.
var Endpoints = []Endpoint{
	{
		ID: "enrollAdministrator", Method: "POST", Path: "/auth/enroll",
		Authenticated: false, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "CredentialsRequest", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeBootstrapTokenInvalid},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeEnrollmentClosed},
			429: {ErrorCodeRateLimited},
			500: {ErrorCodeInternalError},
		},
	},
	{
		ID: "login", Method: "POST", Path: "/auth/login",
		Authenticated: false, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "CredentialsRequest", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			429: {ErrorCodeRateLimited},
			500: {ErrorCodeInternalError},
		},
	},
	{
		ID: "logout", Method: "POST", Path: "/auth/logout",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
		},
	},
	{
		ID: "rotatePassword", Method: "POST", Path: "/auth/password",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "RotatePasswordRequest", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			429: {ErrorCodeRateLimited},
			500: {ErrorCodeInternalError},
		},
	},
	{
		ID: "getSession", Method: "GET", Path: "/auth/session",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "SessionResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "listBackupSets", Method: "GET", Path: "/backup-sets",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListBackupSetsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "createBackupSet", Method: "POST", Path: "/backup-sets",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "CreateBackupSetRequest", ResponseSchema: "CreateBackupSetResponse", SuccessStatus: 201,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeDestructiveOperationsDisabled},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "testCandidateConnection", Method: "POST", Path: "/backup-sets/test-connection",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "TestConnectionRequest", ResponseSchema: "TestConnectionResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getBackupSet", Method: "GET", Path: "/backup-sets/{id}",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "BackupSet", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "applyRetention", Method: "POST", Path: "/backup-sets/{source}/{set}/retention/apply",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: true, Concurrency: "inventory_revision+config_revision",
		RequestSchema: "ApplyRetentionRequest", ResponseSchema: "RetentionPlan", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeDestructiveOperationsDisabled},
			404: {ErrorCodeBackupSetNotFound, ErrorCodeRetentionPlanNotFound},
			409: {ErrorCodeRetentionPlanStale, ErrorCodeRetentionApplyBusy},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "previewRetention", Method: "GET", Path: "/backup-sets/{source}/{set}/retention/preview",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "inventory_revision+config_revision",
		RequestSchema: "", ResponseSchema: "RetentionPlan", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "submitOperation", Method: "POST", Path: "/operations",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "required", DestructiveGate: true, Concurrency: "config_revision",
		RequestSchema: "SubmitOperationRequest", ResponseSchema: "Operation", SuccessStatus: 202,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeDestructiveOperationsDisabled},
			409: {ErrorCodeConfigRevisionStale, ErrorCodeIdempotencyKeyConflict, ErrorCodeOperationAlreadyRunning},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getOperation", Method: "GET", Path: "/operations/{id}",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "Operation", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeOperationNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getSettings", Method: "GET", Path: "/settings",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "SettingsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "updateSettings", Method: "PATCH", Path: "/settings",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "UpdateSettingsRequest", ResponseSchema: "SettingsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "importSSHKey", Method: "POST", Path: "/ssh-keys",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "ImportSSHKeyRequest", ResponseSchema: "ImportSSHKeyResponse", SuccessStatus: 201,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "probeHostKey", Method: "POST", Path: "/ssh/host-key-probe",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "HostKeyProbeRequest", ResponseSchema: "HostKeyProbeResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeHostKeyProbeFailed},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getSystemCapabilities", Method: "GET", Path: "/system/capabilities",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "CapabilitiesResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "listStorageStatus", Method: "GET", Path: "/system/storage",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListStorageStatusResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getSystemVersion", Method: "GET", Path: "/system/version",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "VersionResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "listValidators", Method: "GET", Path: "/validators",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListValidatorsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
}

// CapabilityFields is the platform-capability set GET /system/capabilities
// reports, as wire field names. ui/shared's PlatformCapabilities is held to
// exactly this list, so the two capability models cannot diverge.
var CapabilityFields = []string{
	"native_auth",
	"native_notifications",
	"storage_picker",
	"embedded_window",
	"app_store_packaging",
}

// ApplyRetentionRequest is POST /backup-sets/{source}/{set}/retention/apply.
type ApplyRetentionRequest struct {
	PlanID string `json:"plan_id"`
}

// AuthErrorResponse is the FLAT error body the /auth operations return, with the
// correlation id in the body as well as the header. Deliberately
// recorded as a second shape rather than pretended away:
// apps/common/auth/local diverged from the envelope above before
// this contract existed.
type AuthErrorResponse struct {
	Code          ErrorCode `json:"code"`
	CorrelationID string    `json:"correlationId"`
	Message       string    `json:"message"`
}

// BackupSet is A persisted backup set as the API reports it.
type BackupSet struct {
	CompletionStrategy string   `json:"completion_strategy"`
	Disabled           bool     `json:"disabled"`
	Host               string   `json:"host"`
	ID                 string   `json:"id"`
	Include            []string `json:"include"`
	LocalPath          string   `json:"local_path"`
	Name               string   `json:"name"`
	Port               int      `json:"port"`
	RemotePath         string   `json:"remote_path"`
	SourceName         string   `json:"source_name"`
	User               string   `json:"user"`
	ValidatorID        string   `json:"validator_id"`
}

// CapabilitiesResponse is GET /system/capabilities. The API expression of the
// PlatformCapabilities contract (apps/common/platform/capabilities).
// A capability says what a platform CAN do; it never says who MAY do
// it, and server-side authorization never consults it.
type CapabilitiesResponse struct {
	AppStorePackaging   bool   `json:"app_store_packaging"`
	EmbeddedWindow      bool   `json:"embedded_window"`
	NativeAuth          bool   `json:"native_auth"`
	NativeNotifications bool   `json:"native_notifications"`
	Platform            string `json:"platform"`
	StoragePicker       bool   `json:"storage_picker"`
}

// ConfigRevisionStaleResponse is the CONFIG_REVISION_STALE 409 body. It carries the current
// revision as a structured field so a client retries against a value
// it can rely on rather than one parsed out of prose.
type ConfigRevisionStaleResponse struct {
	ConfigRevision string    `json:"config_revision"`
	Error          ErrorBody `json:"error"`
}

// CreateBackupSetRequest is POST /backup-sets. ssh_key_id and known_hosts_line carry
// REFERENCES produced by /ssh-keys and /ssh/host-key-probe, never
// key material.
type CreateBackupSetRequest struct {
	CompletionStrategy string   `json:"completion_strategy"`
	Disabled           bool     `json:"disabled"`
	Host               string   `json:"host"`
	Include            []string `json:"include"`
	KnownHostsLine     string   `json:"known_hosts_line"`
	LocalPath          string   `json:"local_path"`
	Name               string   `json:"name"`
	Port               int      `json:"port"`
	RemotePath         string   `json:"remote_path"`
	RunImmediately     bool     `json:"run_immediately"`
	SourceName         string   `json:"source_name"`
	SSHKeyID           string   `json:"ssh_key_id"`
	StableForSeconds   int      `json:"stable_for_seconds"`
	StaleAfterSeconds  int      `json:"stale_after_seconds"`
	User               string   `json:"user"`
	ValidatorID        string   `json:"validator_id"`
}

// CreateBackupSetResponse is POST /backup-sets. The created set, plus at most one of operation
// (the run_immediately branch started) or run_error (it did not).
// Always 201: the set itself exists either way.
type CreateBackupSetResponse struct {
	BackupSet
	Operation *Operation `json:"operation,omitempty"`
	RunError  string     `json:"run_error,omitempty"`
}

// CredentialsRequest is POST /auth/login and POST /auth/enroll. camelCase, unlike every
// schema above: apps/common/auth/local predates the snake_case
// convention the rest of /api/v1 uses. Recorded here as it is rather
// than silently normalised; see docs/api/contract.md for why fixing
// it is a separate issue.
type CredentialsRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ErrorBody is the nested error body every operation outside /auth returns. code
// is stable and machine-readable; message is human-readable and MAY
// change without notice.
type ErrorBody struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorResponse is the error envelope every operation outside /auth returns. The
// correlation id travels in the X-Correlation-Id response header.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// HostKeyProbeRequest is POST /ssh/host-key-probe. Opens a real outbound connection, trusts
// nothing.
type HostKeyProbeRequest struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// HostKeyProbeResponse is what the server actually saw. Presenting it to an operator for
// approval is the caller's job.
type HostKeyProbeResponse struct {
	Algorithm      string `json:"algorithm"`
	Fingerprint    string `json:"fingerprint"`
	KnownHostsLine string `json:"known_hosts_line"`
}

// ImportSSHKeyRequest is POST /ssh-keys. Sent once; the caller discards its own copy
// immediately.
type ImportSSHKeyRequest struct {
	PrivateKeyPEM string `json:"private_key_pem"`
}

// ImportSSHKeyResponse is the reference a later create-backup-set call carries instead of
// key material.
type ImportSSHKeyResponse struct {
	Algorithm   string `json:"algorithm"`
	Fingerprint string `json:"fingerprint"`
	ID          string `json:"id"`
}

// ListBackupSetsResponse is GET /backup-sets. An object with one array field, never a bare
// top-level array.
type ListBackupSetsResponse struct {
	BackupSets []BackupSet `json:"backup_sets"`
}

// ListStorageStatusResponse is GET /system/storage.
type ListStorageStatusResponse struct {
	BackupSets []StorageStatus `json:"backup_sets"`
}

// ListValidatorsResponse is GET /validators. Read-only by design: a client-extensible catalog
// would be an arbitrary-command surface.
type ListValidatorsResponse struct {
	Validators []Validator `json:"validators"`
}

// Operation is one durable operation record. Timestamp fields are omitted, not
// zero-valued, until the event they name has happened.
type Operation struct {
	Action         string `json:"action,omitempty"`
	Actor          string `json:"actor,omitempty"`
	BackupSetID    string `json:"backup_set_id,omitempty"`
	ConfigRevision string `json:"config_revision,omitempty"`
	CreatedAt      string `json:"created_at,omitempty"`
	Error          string `json:"error,omitempty"`
	FinishedAt     string `json:"finished_at,omitempty"`
	OperationID    string `json:"operation_id"`
	Result         string `json:"result,omitempty"`
	StartedAt      string `json:"started_at,omitempty"`
	Status         string `json:"status"`
}

// RetentionPlan is A server-computed retention plan. The client may only apply one by
// id; it never proposes what to delete.
type RetentionPlan struct {
	BackupSetID       string             `json:"backup_set_id"`
	ConfigRevision    string             `json:"config_revision"`
	DeleteCount       int                `json:"delete_count"`
	ExpiresAt         string             `json:"expires_at"`
	InventoryRevision string             `json:"inventory_revision"`
	KeepCount         int                `json:"keep_count"`
	OperationID       string             `json:"operation_id,omitempty"`
	PlanID            string             `json:"plan_id"`
	ReclaimBytes      int64              `json:"reclaim_bytes"`
	Verdicts          []RetentionVerdict `json:"verdicts"`
}

// RetentionSchema is the closed value sets and bounds a retention chain is validated
// against, served rather than transcribed into a frontend.
type RetentionSchema struct {
	DefaultTiers     []RetentionTier `json:"default_tiers"`
	Granularities    []string        `json:"granularities"`
	KeepMax          int             `json:"keep_max"`
	PeriodDaysMax    int             `json:"period_days_max"`
	ReservedTierName string          `json:"reserved_tier_name"`
	TierNamePattern  string          `json:"tier_name_pattern"`
	WindowUnits      []string        `json:"window_units"`
}

// RetentionSettings is the retention policy actually in effect. tiers is always the
// RESOLVED chain.
type RetentionSettings struct {
	ProtectLastKnownGood bool            `json:"protect_last_known_good"`
	Tiers                []RetentionTier `json:"tiers"`
	Timezone             string          `json:"timezone"`
	WeekStartsOn         string          `json:"week_starts_on"`
}

// RetentionTier is one link in the retention chain, on the wire. The same shape is
// read and written, so a client round-trips exactly what it was
// served.
type RetentionTier struct {
	Granularity string `json:"granularity"`
	Keep        int    `json:"keep"`
	Name        string `json:"name"`
	PeriodDays  int    `json:"period_days,omitempty"`
	WindowUnit  string `json:"window_unit,omitempty"`
}

// RetentionVerdict is what the plan decided for one artifact, and why.
type RetentionVerdict struct {
	Action   string   `json:"action"`
	Artifact string   `json:"artifact"`
	Reason   string   `json:"reason"`
	Tiers    []string `json:"tiers,omitempty"`
}

// RotatePasswordRequest is POST /auth/password. Requires an already-authenticated session AND
// the current password: holding a cookie is not enough.
type RotatePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// SessionResponse is GET /auth/session.
type SessionResponse struct {
	Username string `json:"username"`
}

// SettingsResponse is GET and PATCH /settings both return this: the settings now in
// effect plus the rules they were validated against.
type SettingsResponse struct {
	Retention RetentionSettings `json:"retention"`
	Schema    SettingsSchema    `json:"schema"`
}

// SettingsSchema is the schema half of the settings response.
type SettingsSchema struct {
	Retention RetentionSchema `json:"retention"`
}

// StorageStatus is one backup set's capacity assessment.
type StorageStatus struct {
	Available         bool   `json:"available"`
	AvailableBytes    uint64 `json:"available_bytes"`
	BackupSetID       string `json:"backup_set_id"`
	CriticalFreeBytes uint64 `json:"critical_free_bytes"`
	FreeBytes         uint64 `json:"free_bytes"`
	Level             string `json:"level"`
	LocalPath         string `json:"local_path"`
	TotalBytes        uint64 `json:"total_bytes"`
	UnavailableReason string `json:"unavailable_reason"`
	WarningFreeBytes  uint64 `json:"warning_free_bytes"`
}

// SubmitOperationRequest is POST /operations. The idempotency key is a header, not a body
// field: it is a property of the retry, not of the operation.
type SubmitOperationRequest struct {
	Action         string `json:"action"`
	ConfigRevision string `json:"config_revision"`
}

// TestConnectionRequest is POST /backup-sets/test-connection. A pre-save reachability and
// authentication check, before a backup set has an id.
type TestConnectionRequest struct {
	Host           string `json:"host"`
	KnownHostsLine string `json:"known_hosts_line"`
	Port           int    `json:"port"`
	RemotePath     string `json:"remote_path"`
	SSHKeyID       string `json:"ssh_key_id"`
	User           string `json:"user"`
}

// TestConnectionResponse is the outcome of a pre-save connection test.
type TestConnectionResponse struct {
	Message string `json:"message,omitempty"`
	OK      bool   `json:"ok"`
}

// UpdateRetentionSettings is A PARTIAL retention update. An omitted field is left exactly as
// the running configuration has it; omitting tiers leaves the chain,
// and a legacy file's own spelling of it, untouched.
type UpdateRetentionSettings struct {
	ProtectLastKnownGood *bool           `json:"protect_last_known_good"`
	Tiers                []RetentionTier `json:"tiers"`
	Timezone             *string         `json:"timezone"`
	WeekStartsOn         *string         `json:"week_starts_on"`
}

// UpdateSettingsRequest is PATCH /settings. An enumerated request type, never a configuration
// passthrough.
type UpdateSettingsRequest struct {
	Retention *UpdateRetentionSettings `json:"retention"`
}

// Validator is one registered application validator. An id and a sentence, and
// deliberately nothing else: the script it resolves to is
// server-side and a client never learns it.
type Validator struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

// VersionResponse is GET /system/version. Nothing here names an implementation: no
// rclone, no SQLite, no filesystem path.
type VersionResponse struct {
	APIVersion     string `json:"api_version"`
	Commit         string `json:"commit"`
	ConfigRevision string `json:"config_revision"`
	CoreVersion    string `json:"core_version"`
	EngineVersion  string `json:"engine_version"`
	GoVersion      string `json:"go_version"`
	Ready          bool   `json:"ready"`
}

// SchemaTypes maps a contract schema name to a zero value of the generated
// Go type for it. A conformance test reaches a type by contract name
// through this map rather than through a hand-written lookup, so a schema
// added to the contract cannot quietly go unchecked.
var SchemaTypes = map[string]any{
	"ApplyRetentionRequest":       ApplyRetentionRequest{},
	"AuthErrorResponse":           AuthErrorResponse{},
	"BackupSet":                   BackupSet{},
	"CapabilitiesResponse":        CapabilitiesResponse{},
	"ConfigRevisionStaleResponse": ConfigRevisionStaleResponse{},
	"CreateBackupSetRequest":      CreateBackupSetRequest{},
	"CreateBackupSetResponse":     CreateBackupSetResponse{},
	"CredentialsRequest":          CredentialsRequest{},
	"ErrorBody":                   ErrorBody{},
	"ErrorResponse":               ErrorResponse{},
	"HostKeyProbeRequest":         HostKeyProbeRequest{},
	"HostKeyProbeResponse":        HostKeyProbeResponse{},
	"ImportSSHKeyRequest":         ImportSSHKeyRequest{},
	"ImportSSHKeyResponse":        ImportSSHKeyResponse{},
	"ListBackupSetsResponse":      ListBackupSetsResponse{},
	"ListStorageStatusResponse":   ListStorageStatusResponse{},
	"ListValidatorsResponse":      ListValidatorsResponse{},
	"Operation":                   Operation{},
	"RetentionPlan":               RetentionPlan{},
	"RetentionSchema":             RetentionSchema{},
	"RetentionSettings":           RetentionSettings{},
	"RetentionTier":               RetentionTier{},
	"RetentionVerdict":            RetentionVerdict{},
	"RotatePasswordRequest":       RotatePasswordRequest{},
	"SessionResponse":             SessionResponse{},
	"SettingsResponse":            SettingsResponse{},
	"SettingsSchema":              SettingsSchema{},
	"StorageStatus":               StorageStatus{},
	"SubmitOperationRequest":      SubmitOperationRequest{},
	"TestConnectionRequest":       TestConnectionRequest{},
	"TestConnectionResponse":      TestConnectionResponse{},
	"UpdateRetentionSettings":     UpdateRetentionSettings{},
	"UpdateSettingsRequest":       UpdateSettingsRequest{},
	"Validator":                   Validator{},
	"VersionResponse":             VersionResponse{},
}
