// Code generated by scripts/api/gen-bindings.go from api/v1/openapi.json. DO NOT EDIT.
//
// Package apicontract is the Go half of the generated /api/v1 bindings
// (issue #166). The contract document, not this file and not the handlers
// in apps/common/webhost, is the definition of the boundary: edit
// api/v1/openapi.json and re-run scripts/api/generate.sh.
//
// A hand edit here is caught by scripts/api/check-contract-drift.sh, which
// regenerates into a temporary directory and compares. A handler whose
// shape stops matching one of these types is caught by
// apps/common/webhost's TestContract_HandlerShapesMatchTheContract.
package apicontract

// Version and BasePath are the versioned boundary itself.
const (
	Version  = "v1"
	BasePath = "/api/v1"
)

// ContractSHA256 is the digest of the contract document these bindings were
// generated from.
//
// It exists so the ordinary go test run catches the commonest
// mistake, editing the contract and forgetting to regenerate, without
// shelling out to the generator: TestContract_TheBindingsWereGeneratedFromThisContract
// hashes api/v1/openapi.json and compares. The full byte-for-byte
// comparison still lives in scripts/api/check-contract-drift.sh, which is
// the only thing that can also catch a hand edit to the body of this file.
const ContractSHA256 = "28f1ff6250f38ee2569227b97e3e0db6061448d929b5e6d951457c93cf0fbc1c"

// ErrorCode is a stable, machine-readable failure token. The human-readable
// message beside it on the wire MAY change without notice; this may not.
type ErrorCode string

// The complete error-code registry. Codes are declared in the contract, not
// here, and ui/shared reads the same registry through the TypeScript half of
// these bindings, so the two can never hold different lists.
const (
	ErrorCodeAuthenticationFailed          ErrorCode = "authentication-failed"
	ErrorCodeSSHHostKeyChanged             ErrorCode = "ssh-host-key-changed"
	ErrorCodePermissionDenied              ErrorCode = "permission-denied"
	ErrorCodeRemotePathMissing             ErrorCode = "remote-path-missing"
	ErrorCodeChecksumMismatch              ErrorCode = "checksum-mismatch"
	ErrorCodeBackupStale                   ErrorCode = "backup-stale"
	ErrorCodeStorageCritical               ErrorCode = "storage-critical"
	ErrorCodeVersionMismatch               ErrorCode = "version-mismatch"
	ErrorCodeOperationConflict             ErrorCode = "operation-conflict"
	ErrorCodeUnknown                       ErrorCode = "unknown"
	ErrorCodeUnauthenticated               ErrorCode = "UNAUTHENTICATED"
	ErrorCodeRateLimited                   ErrorCode = "RATE_LIMITED"
	ErrorCodeInvalidRequest                ErrorCode = "INVALID_REQUEST"
	ErrorCodeEnrollmentClosed              ErrorCode = "ENROLLMENT_CLOSED"
	ErrorCodeBootstrapTokenInvalid         ErrorCode = "BOOTSTRAP_TOKEN_INVALID"
	ErrorCodeInternalError                 ErrorCode = "INTERNAL_ERROR"
	ErrorCodeCSRFTokenMissing              ErrorCode = "CSRF_TOKEN_MISSING"
	ErrorCodeCSRFTokenMismatch             ErrorCode = "CSRF_TOKEN_MISMATCH"
	ErrorCodeRetentionPlanStale            ErrorCode = "RETENTION_PLAN_STALE"
	ErrorCodeRetentionPlanNotFound         ErrorCode = "RETENTION_PLAN_NOT_FOUND"
	ErrorCodeRetentionApplyBusy            ErrorCode = "RETENTION_APPLY_BUSY"
	ErrorCodeBackupSetNotFound             ErrorCode = "BACKUP_SET_NOT_FOUND"
	ErrorCodeOperationNotFound             ErrorCode = "OPERATION_NOT_FOUND"
	ErrorCodeOperationAlreadyRunning       ErrorCode = "OPERATION_ALREADY_RUNNING"
	ErrorCodeIdempotencyKeyConflict        ErrorCode = "IDEMPOTENCY_KEY_CONFLICT"
	ErrorCodeConfigRevisionStale           ErrorCode = "CONFIG_REVISION_STALE"
	ErrorCodeSSHKeyNotFound                ErrorCode = "SSH_KEY_NOT_FOUND"
	ErrorCodeHostKeyProbeFailed            ErrorCode = "HOST_KEY_PROBE_FAILED"
	ErrorCodeDestructiveOperationsDisabled ErrorCode = "DESTRUCTIVE_OPERATIONS_DISABLED"
	ErrorCodeInternal                      ErrorCode = "INTERNAL"
	ErrorCodeAlreadyConfigured             ErrorCode = "ALREADY_CONFIGURED"
	ErrorCodeNotConfigured                 ErrorCode = "NOT_CONFIGURED"
	ErrorCodeArtifactNotFound              ErrorCode = "ARTIFACT_NOT_FOUND"
	ErrorCodeArtifactNotQuarantined        ErrorCode = "ARTIFACT_NOT_QUARANTINED"
	ErrorCodeArtifactIrrecoverable         ErrorCode = "ARTIFACT_IRRECOVERABLE"
	ErrorCodeReinstatementRefused          ErrorCode = "REINSTATEMENT_REFUSED"
)

// WireErrorCodes is codes a server may put on the wire. Every one of these is emitted by real handler code, and apps/common/webhost's TestContract_EveryWireErrorCodeIsRegistered holds that both ways.
var WireErrorCodes = []ErrorCode{
	ErrorCodeUnauthenticated,
	ErrorCodeRateLimited,
	ErrorCodeInvalidRequest,
	ErrorCodeEnrollmentClosed,
	ErrorCodeBootstrapTokenInvalid,
	ErrorCodeInternalError,
	ErrorCodeCSRFTokenMissing,
	ErrorCodeCSRFTokenMismatch,
	ErrorCodeRetentionPlanStale,
	ErrorCodeRetentionPlanNotFound,
	ErrorCodeRetentionApplyBusy,
	ErrorCodeBackupSetNotFound,
	ErrorCodeOperationNotFound,
	ErrorCodeOperationAlreadyRunning,
	ErrorCodeIdempotencyKeyConflict,
	ErrorCodeConfigRevisionStale,
	ErrorCodeSSHKeyNotFound,
	ErrorCodeHostKeyProbeFailed,
	ErrorCodeDestructiveOperationsDisabled,
	ErrorCodeInternal,
	ErrorCodeAlreadyConfigured,
	ErrorCodeNotConfigured,
	ErrorCodeArtifactNotFound,
	ErrorCodeArtifactNotQuarantined,
	ErrorCodeArtifactIrrecoverable,
	ErrorCodeReinstatementRefused,
}

// UIErrorCodes is the shared UI's own presentation vocabulary. No endpoint emits these; they are registered here so there is one registry rather than a second hand-maintained list in ui/shared.
var UIErrorCodes = []ErrorCode{
	ErrorCodeAuthenticationFailed,
	ErrorCodeSSHHostKeyChanged,
	ErrorCodePermissionDenied,
	ErrorCodeRemotePathMissing,
	ErrorCodeChecksumMismatch,
	ErrorCodeBackupStale,
	ErrorCodeStorageCritical,
	ErrorCodeVersionMismatch,
	ErrorCodeOperationConflict,
	ErrorCodeUnknown,
}

// ErrorCodes is every registered code, wire and UI alike, in contract order.
var ErrorCodes = []ErrorCode{
	ErrorCodeAuthenticationFailed,
	ErrorCodeSSHHostKeyChanged,
	ErrorCodePermissionDenied,
	ErrorCodeRemotePathMissing,
	ErrorCodeChecksumMismatch,
	ErrorCodeBackupStale,
	ErrorCodeStorageCritical,
	ErrorCodeVersionMismatch,
	ErrorCodeOperationConflict,
	ErrorCodeUnknown,
	ErrorCodeUnauthenticated,
	ErrorCodeRateLimited,
	ErrorCodeInvalidRequest,
	ErrorCodeEnrollmentClosed,
	ErrorCodeBootstrapTokenInvalid,
	ErrorCodeInternalError,
	ErrorCodeCSRFTokenMissing,
	ErrorCodeCSRFTokenMismatch,
	ErrorCodeRetentionPlanStale,
	ErrorCodeRetentionPlanNotFound,
	ErrorCodeRetentionApplyBusy,
	ErrorCodeBackupSetNotFound,
	ErrorCodeOperationNotFound,
	ErrorCodeOperationAlreadyRunning,
	ErrorCodeIdempotencyKeyConflict,
	ErrorCodeConfigRevisionStale,
	ErrorCodeSSHKeyNotFound,
	ErrorCodeHostKeyProbeFailed,
	ErrorCodeDestructiveOperationsDisabled,
	ErrorCodeInternal,
	ErrorCodeAlreadyConfigured,
	ErrorCodeNotConfigured,
	ErrorCodeArtifactNotFound,
	ErrorCodeArtifactNotQuarantined,
	ErrorCodeArtifactIrrecoverable,
	ErrorCodeReinstatementRefused,
}

// ErrorClasses groups codes by the refusal they represent, so a caller (or
// a red team) can assert the RIGHT refusal rather than any refusal.
var ErrorClasses = map[string][]ErrorCode{
	"authentication": {ErrorCodeUnauthenticated, ErrorCodeBootstrapTokenInvalid},
	"authorization":  {ErrorCodeEnrollmentClosed, ErrorCodeDestructiveOperationsDisabled, ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
	"conflict":       {ErrorCodeRetentionPlanStale, ErrorCodeRetentionApplyBusy, ErrorCodeOperationAlreadyRunning, ErrorCodeIdempotencyKeyConflict, ErrorCodeConfigRevisionStale, ErrorCodeAlreadyConfigured, ErrorCodeArtifactNotQuarantined, ErrorCodeArtifactIrrecoverable, ErrorCodeReinstatementRefused},
	"internal":       {ErrorCodeInternal, ErrorCodeInternalError},
	"not-found":      {ErrorCodeBackupSetNotFound, ErrorCodeOperationNotFound, ErrorCodeRetentionPlanNotFound, ErrorCodeArtifactNotFound},
	"throttling":     {ErrorCodeRateLimited},
	"unavailable":    {ErrorCodeNotConfigured},
	"validation":     {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound, ErrorCodeHostKeyProbeFailed},
}

// Endpoint is one operation of the contract, with the requirements a
// handler has to satisfy expressed as data rather than as convention:
// whether a session is required, whether CSRF is required, whether an
// idempotency key is required, whether the destructive gate stands in
// front of it, and which optimistic-concurrency token it reads.
type Endpoint struct {
	ID              string
	Method          string
	Path            string
	Authenticated   bool
	CSRFRequired    bool
	IdempotencyKey  string
	DestructiveGate bool
	Concurrency     string
	RequestSchema   string
	ResponseSchema  string
	SuccessStatus   int
	ErrorCodes      map[int][]ErrorCode
}

// Endpoints is every operation the contract declares, ordered by path then
// method.
var Endpoints = []Endpoint{
	{
		ID: "listActivity", Method: "GET", Path: "/activity",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListActivityResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "enrollAdministrator", Method: "POST", Path: "/auth/enroll",
		Authenticated: false, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "CredentialsRequest", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeBootstrapTokenInvalid},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeEnrollmentClosed},
			429: {ErrorCodeRateLimited},
			500: {ErrorCodeInternalError},
		},
	},
	{
		ID: "login", Method: "POST", Path: "/auth/login",
		Authenticated: false, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "CredentialsRequest", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			429: {ErrorCodeRateLimited},
			500: {ErrorCodeInternalError},
		},
	},
	{
		ID: "logout", Method: "POST", Path: "/auth/logout",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
		},
	},
	{
		ID: "rotatePassword", Method: "POST", Path: "/auth/password",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "RotatePasswordRequest", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			429: {ErrorCodeRateLimited},
			500: {ErrorCodeInternalError},
		},
	},
	{
		ID: "getSession", Method: "GET", Path: "/auth/session",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "SessionResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "listBackupSets", Method: "GET", Path: "/backup-sets",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListBackupSetsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "createBackupSet", Method: "POST", Path: "/backup-sets",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "CreateBackupSetRequest", ResponseSchema: "CreateBackupSetResponse", SuccessStatus: 201,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeDestructiveOperationsDisabled},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "testCandidateConnection", Method: "POST", Path: "/backup-sets/test-connection",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "TestConnectionRequest", ResponseSchema: "TestConnectionResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getBackupSet", Method: "GET", Path: "/backup-sets/{id}",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "BackupSet", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "updateBackupSet", Method: "PATCH", Path: "/backup-sets/{source}/{set}",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "UpdateBackupSetRequest", ResponseSchema: "BackupSet", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getBackupSetEditHold", Method: "GET", Path: "/backup-sets/{source}/{set}/edit-hold",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "BackupSetEditHoldState", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "takeBackupSetEditHold", Method: "POST", Path: "/backup-sets/{source}/{set}/edit-hold",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "BackupSetEditHold", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "releaseBackupSetEditHold", Method: "POST", Path: "/backup-sets/{source}/{set}/edit-hold/release",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "setBackupSetEnabled", Method: "POST", Path: "/backup-sets/{source}/{set}/enabled",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "SetEnabledRequest", ResponseSchema: "BackupSet", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "setBackupSetReadOnly", Method: "POST", Path: "/backup-sets/{source}/{set}/read-only",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "SetReadOnlyRequest", ResponseSchema: "BackupSet", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "applyRetention", Method: "POST", Path: "/backup-sets/{source}/{set}/retention/apply",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: true, Concurrency: "inventory_revision+config_revision",
		RequestSchema: "ApplyRetentionRequest", ResponseSchema: "RetentionPlan", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeDestructiveOperationsDisabled},
			404: {ErrorCodeBackupSetNotFound, ErrorCodeRetentionPlanNotFound},
			409: {ErrorCodeRetentionPlanStale, ErrorCodeRetentionApplyBusy},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "previewRetention", Method: "GET", Path: "/backup-sets/{source}/{set}/retention/preview",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "inventory_revision+config_revision",
		RequestSchema: "", ResponseSchema: "RetentionPlan", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "listArtifacts", Method: "GET", Path: "/backups",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListArtifactsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeBackupSetNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getArtifact", Method: "GET", Path: "/backups/{id}",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "Artifact", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeArtifactNotFound},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "rebuildCatalog", Method: "POST", Path: "/catalog/rebuild",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "CatalogReportResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "scanCatalog", Method: "POST", Path: "/catalog/scan",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "CatalogReportResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "listOperations", Method: "GET", Path: "/operations",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListOperationsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "submitOperation", Method: "POST", Path: "/operations",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "required", DestructiveGate: true, Concurrency: "config_revision",
		RequestSchema: "SubmitOperationRequest", ResponseSchema: "Operation", SuccessStatus: 202,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch, ErrorCodeDestructiveOperationsDisabled},
			409: {ErrorCodeConfigRevisionStale, ErrorCodeIdempotencyKeyConflict, ErrorCodeOperationAlreadyRunning},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "getOperation", Method: "GET", Path: "/operations/{id}",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "Operation", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			404: {ErrorCodeOperationNotFound},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "listQuarantine", Method: "GET", Path: "/quarantine",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListArtifactsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "reinstateArtifact", Method: "POST", Path: "/quarantine/{id}/reinstate",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ArtifactReinstateResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeArtifactNotFound},
			409: {ErrorCodeArtifactNotQuarantined, ErrorCodeReinstatementRefused},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "retryArtifactIngestion", Method: "POST", Path: "/quarantine/{id}/retry",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "", SuccessStatus: 204,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeArtifactNotFound},
			409: {ErrorCodeArtifactNotQuarantined, ErrorCodeArtifactIrrecoverable},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "revalidateArtifact", Method: "POST", Path: "/quarantine/{id}/revalidate",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ArtifactCheckResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			404: {ErrorCodeArtifactNotFound},
			409: {ErrorCodeArtifactNotQuarantined},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getSettings", Method: "GET", Path: "/settings",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "SettingsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "updateSettings", Method: "PATCH", Path: "/settings",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "UpdateSettingsRequest", ResponseSchema: "SettingsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "importSSHKey", Method: "POST", Path: "/ssh-keys",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "ImportSSHKeyRequest", ResponseSchema: "ImportSSHKeyResponse", SuccessStatus: 201,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "probeHostKey", Method: "POST", Path: "/ssh/host-key-probe",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "HostKeyProbeRequest", ResponseSchema: "HostKeyProbeResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeHostKeyProbeFailed},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getSystemCapabilities", Method: "GET", Path: "/system/capabilities",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "CapabilitiesResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "getFirstRunStatus", Method: "GET", Path: "/system/first-run",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "FirstRunStatusResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "completeFirstRun", Method: "POST", Path: "/system/first-run",
		Authenticated: true, CSRFRequired: true, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "BackupSetSpec", ResponseSchema: "CompleteFirstRunResponse", SuccessStatus: 201,
		ErrorCodes: map[int][]ErrorCode{
			400: {ErrorCodeInvalidRequest, ErrorCodeSSHKeyNotFound},
			401: {ErrorCodeUnauthenticated},
			403: {ErrorCodeCSRFTokenMissing, ErrorCodeCSRFTokenMismatch},
			409: {ErrorCodeAlreadyConfigured},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "getSystemHealth", Method: "GET", Path: "/system/health",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "HealthResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
	{
		ID: "listStorageStatus", Method: "GET", Path: "/system/storage",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListStorageStatusResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
			503: {ErrorCodeNotConfigured},
		},
	},
	{
		ID: "getSystemVersion", Method: "GET", Path: "/system/version",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "VersionResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
		},
	},
	{
		ID: "listValidators", Method: "GET", Path: "/validators",
		Authenticated: true, CSRFRequired: false, IdempotencyKey: "none", DestructiveGate: false, Concurrency: "",
		RequestSchema: "", ResponseSchema: "ListValidatorsResponse", SuccessStatus: 200,
		ErrorCodes: map[int][]ErrorCode{
			401: {ErrorCodeUnauthenticated},
			500: {ErrorCodeInternal},
		},
	},
}

// CapabilityFields is the platform-capability set GET /system/capabilities
// reports, as wire field names. ui/shared's PlatformCapabilities is held to
// exactly this list, so the two capability models cannot diverge.
var CapabilityFields = []string{
	"native_auth",
	"native_notifications",
	"storage_picker",
	"embedded_window",
	"app_store_packaging",
}

// ActivityEvent is one recorded lifecycle moment: a backup moved from one state to
// another. This is a read of the durable, append-only transition
// record, not a second event stream.
type ActivityEvent struct {
	ArtifactID   string `json:"artifact_id"`
	ArtifactName string `json:"artifact_name"`
	BackupSetID  string `json:"backup_set_id"`
	Detail       string `json:"detail,omitempty"`
	From         string `json:"from,omitempty"`
	OccurredAt   string `json:"occurred_at"`
	SetName      string `json:"set_name"`
	SourceName   string `json:"source_name"`
	To           string `json:"to"`
}

// ApplyRetentionRequest is POST /backup-sets/{source}/{set}/retention/apply.
type ApplyRetentionRequest struct {
	PlanID string `json:"plan_id"`
}

// Artifact is one backup this deployment holds, as the API reports it. Nothing
// here names an implementation: the fields describe a backup's
// identity, freshness and trustworthiness, never how it is stored.
type Artifact struct {
	BackupSetID             string `json:"backup_set_id"`
	Checksum                string `json:"checksum,omitempty"`
	ChecksumAlgorithm       string `json:"checksum_algorithm,omitempty"`
	DiscoveredAt            string `json:"discovered_at"`
	ID                      string `json:"id"`
	LocalPath               string `json:"local_path"`
	Name                    string `json:"name"`
	QuarantineIrrecoverable bool   `json:"quarantine_irrecoverable"`
	QuarantineReason        string `json:"quarantine_reason,omitempty"`
	Quarantined             bool   `json:"quarantined"`
	RemotePath              string `json:"remote_path"`
	RemoteSourceRemovedAt   string `json:"remote_source_removed_at,omitempty"`
	RetentionTier           string `json:"retention_tier,omitempty"`
	SetName                 string `json:"set_name"`
	SizeBytes               int64  `json:"size_bytes"`
	SourceName              string `json:"source_name"`
	State                   string `json:"state"`
	UpdatedAt               string `json:"updated_at"`
	Validation              string `json:"validation"`
	ValidationDetail        string `json:"validation_detail,omitempty"`
}

// ArtifactCheckResponse is the verdict of re-checking one quarantined backup. Nothing is
// written and the backup is not moved: a pass is evidence for an
// operator deciding whether to retry, not a rehabilitation.
type ArtifactCheckResponse struct {
	Checked bool   `json:"checked"`
	Passed  bool   `json:"passed"`
	Reason  string `json:"reason,omitempty"`
}

// ArtifactReinstateResponse is POST /quarantine/{id}/reinstate. Re-checks one quarantined
// backup's durable local copy and, when what it finds is enough,
// returns it to the state it already held so it counts as a restore
// point again. `reinstated` and `passed` are separate: `passed` is
// the verdict of the checks, `reinstated` is whether the backup
// actually moved. A backup reinstated this way NEVER authorises
// deleting its remote source again; that forfeiture is permanent and
// is what makes the action safe to offer.
type ArtifactReinstateResponse struct {
	Checked    bool   `json:"checked"`
	Passed     bool   `json:"passed"`
	Reason     string `json:"reason,omitempty"`
	Reinstated bool   `json:"reinstated"`
	State      string `json:"state,omitempty"`
}

// AuthErrorResponse is the FLAT error body the /auth operations return, with the
// correlation id in the body as well as the header. Deliberately
// recorded as a second shape rather than pretended away:
// apps/common/auth/local diverged from the envelope above before
// this contract existed.
type AuthErrorResponse struct {
	Code          ErrorCode `json:"code"`
	CorrelationID string    `json:"correlationId"`
	Message       string    `json:"message"`
}

// BackupSet is A persisted backup set as the API reports it.
type BackupSet struct {
	CompletionStrategy string   `json:"completion_strategy"`
	Disabled           bool     `json:"disabled"`
	Host               string   `json:"host"`
	ID                 string   `json:"id"`
	Include            []string `json:"include"`
	LocalPath          string   `json:"local_path"`
	Name               string   `json:"name"`
	Port               int      `json:"port"`
	ReadOnly           bool     `json:"read_only"`
	RemotePath         string   `json:"remote_path"`
	SourceName         string   `json:"source_name"`
	StableForSeconds   int      `json:"stable_for_seconds"`
	User               string   `json:"user"`
	ValidatorID        string   `json:"validator_id"`
}

// BackupSetEditHold is POST /backup-sets/{source}/{set}/edit-hold. The lease just taken
// or renewed, plus what taking it interrupted. `stopped` is null
// when nothing was running, so a client never claims to have stopped
// something it did not.
type BackupSetEditHold struct {
	BackupSetID string       `json:"backup_set_id"`
	ExpiresAt   string       `json:"expires_at"`
	Stopped     *RunningWork `json:"stopped"`
}

// BackupSetEditHoldState is GET /backup-sets/{source}/{set}/edit-hold. What entering edit mode
// for this backup set would interrupt, and whether a hold is already
// in force. `running` is null when no cycle is currently inside this
// set, which is what lets a client open edit mode with no prompt for
// a risk that does not exist.
type BackupSetEditHoldState struct {
	BackupSetID string       `json:"backup_set_id"`
	ExpiresAt   string       `json:"expires_at,omitempty"`
	Held        bool         `json:"held"`
	Running     *RunningWork `json:"running"`
}

// BackupSetHealth is one backup set's freshness verdict. This is the backup half of
// health, and it deliberately carries no process or build fact: a
// running service is not evidence that backups are landing.
type BackupSetHealth struct {
	BackupSetID                   string `json:"backup_set_id"`
	CurrentTransfers              int    `json:"current_transfers"`
	Failures                      int    `json:"failures"`
	FreeBytes                     uint64 `json:"free_bytes,omitempty"`
	FreeBytesKnown                bool   `json:"free_bytes_known"`
	HaltReason                    string `json:"halt_reason,omitempty"`
	LastCompletedBackupAt         string `json:"last_completed_backup_at,omitempty"`
	NewestGoodBackupAt            string `json:"newest_good_backup_at,omitempty"`
	PendingDeletes                int    `json:"pending_deletes"`
	QuarantinedCount              int    `json:"quarantined_count"`
	QuarantinedLostCount          int    `json:"quarantined_lost_count"`
	ReadOnlyRetainedCount         int    `json:"read_only_retained_count"`
	Reason                        string `json:"reason"`
	ReinstatedRemoteRetainedCount int    `json:"reinstated_remote_retained_count"`
	SetName                       string `json:"set_name"`
	SourceName                    string `json:"source_name"`
	StaleAfterSeconds             int64  `json:"stale_after_seconds"`
	State                         string `json:"state"`
	StorageLevel                  string `json:"storage_level,omitempty"`
	TotalBytes                    uint64 `json:"total_bytes,omitempty"`
}

// BackupSetSpec is everything it takes to DESCRIBE one backup set: where it reads
// from, where it writes to, how it decides a file is complete, and
// whether it starts enabled. ssh_key_id and known_hosts_line carry
// REFERENCES produced by /ssh-keys and /ssh/host-key-probe, never
// key material. Nothing here asks for anything to be RUN, which is
// what makes it the body of two different operations: POST
// /backup-sets folds a set into a configuration that already exists,
// and POST /system/first-run writes the first configuration there
// has ever been. Those two share this base rather than restating it,
// so the wizard that collects these answers can never be right about
// one operation and wrong about the other.
type BackupSetSpec struct {
	CompletionStrategy string   `json:"completion_strategy"`
	Disabled           bool     `json:"disabled"`
	Host               string   `json:"host"`
	Include            []string `json:"include"`
	KnownHostsLine     string   `json:"known_hosts_line"`
	LocalPath          string   `json:"local_path"`
	Name               string   `json:"name"`
	Port               int      `json:"port"`
	ReadOnly           bool     `json:"read_only"`
	RemotePath         string   `json:"remote_path"`
	SourceName         string   `json:"source_name"`
	SSHKeyID           string   `json:"ssh_key_id"`
	StableForSeconds   int      `json:"stable_for_seconds"`
	StaleAfterSeconds  int      `json:"stale_after_seconds"`
	User               string   `json:"user"`
	ValidatorID        string   `json:"validator_id"`
}

// CapabilitiesResponse is GET /system/capabilities. The API expression of the
// PlatformCapabilities contract (apps/common/platform/capabilities).
// A capability says what a platform CAN do; it never says who MAY do
// it, and server-side authorization never consults it.
type CapabilitiesResponse struct {
	AppStorePackaging   bool   `json:"app_store_packaging"`
	EmbeddedWindow      bool   `json:"embedded_window"`
	NativeAuth          bool   `json:"native_auth"`
	NativeNotifications bool   `json:"native_notifications"`
	Platform            string `json:"platform"`
	StoragePicker       bool   `json:"storage_picker"`
}

// CapacitySettings is FR-21's capacity configuration as it is actually deciding. Every
// number is BYTES: the MB/GB picker beside the field is display only
// and converts at the edge, so nothing on this boundary carries a
// unit.
type CapacitySettings struct {
	BackupRoot           string `json:"backup_root"`
	BackupRootConfigured bool   `json:"backup_root_configured"`
	CapBytes             int64  `json:"cap_bytes"`
	CriticalFreeBytes    int64  `json:"critical_free_bytes"`
	SafetyMarginBytes    int64  `json:"safety_margin_bytes"`
	WarningFreeBytes     int64  `json:"warning_free_bytes"`
}

// CatalogFailure is one recovery manifest a catalog pass could not use.
type CatalogFailure struct {
	BackupSetID string `json:"backup_set_id"`
	Path        string `json:"path,omitempty"`
	Reason      string `json:"reason"`
}

// CatalogReportResponse is POST /catalog/scan and POST /catalog/rebuild. Both return this
// shape, because a scan is the rebuild with nothing written: a
// preview computed by a second implementation would be a preview of
// something else.
type CatalogReportResponse struct {
	AlreadyPresent int              `json:"already_present"`
	DryRun         bool             `json:"dry_run"`
	Failures       []CatalogFailure `json:"failures"`
	Reconstructed  int              `json:"reconstructed"`
	Scanned        int              `json:"scanned"`
}

// CompleteFirstRunResponse is POST /system/first-run. The backup set the first configuration was
// written around, NESTED rather than flattened, which is the one
// place this contract deliberately differs from
// CreateBackupSetResponse beside it. What this operation creates is
// a whole configuration; the set is its first member, and
// restart_required is a fact about the instance, not about the set.
// Keeping backup_set as exactly a BackupSet means a later v1
// addition describing the configuration lands beside it instead of
// becoming indistinguishable from a backup-set field, and can never
// collide with a field BackupSet itself grows.
type CompleteFirstRunResponse struct {
	BackupSet       BackupSet `json:"backup_set"`
	RestartRequired bool      `json:"restart_required"`
}

// ConfigRevisionStaleResponse is the CONFIG_REVISION_STALE 409 body. It carries the current
// revision as a structured field so a client retries against a value
// it can rely on rather than one parsed out of prose.
type ConfigRevisionStaleResponse struct {
	ConfigRevision string    `json:"config_revision"`
	Error          ErrorBody `json:"error"`
}

// CreateBackupSetRequest is POST /backup-sets. The backup-set spec, plus the one thing only a
// create can ask for: that the new set also runs at once.
type CreateBackupSetRequest struct {
	BackupSetSpec
	RunImmediately bool `json:"run_immediately"`
}

// CreateBackupSetResponse is POST /backup-sets. The created set, plus at most one of operation
// (the run_immediately branch started) or run_error (it did not).
// Always 201: the set itself exists either way.
type CreateBackupSetResponse struct {
	BackupSet
	Operation *Operation `json:"operation,omitempty"`
	RunError  string     `json:"run_error,omitempty"`
}

// CredentialsRequest is POST /auth/login and POST /auth/enroll. camelCase, unlike every
// schema above: apps/common/auth/local predates the snake_case
// convention the rest of /api/v1 uses. Recorded here as it is rather
// than silently normalised; see docs/api/contract.md for why fixing
// it is a separate issue.
type CredentialsRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// ErrorBody is the nested error body every operation outside /auth returns. code
// is stable and machine-readable; message is human-readable and MAY
// change without notice.
type ErrorBody struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorResponse is the error envelope every operation outside /auth returns. The
// correlation id travels in the X-Correlation-Id response header.
type ErrorResponse struct {
	Error ErrorBody `json:"error"`
}

// FirstRunStatusResponse is GET /system/first-run. The one question a client asks before it
// decides whether to render the setup flow or the application.
// Deliberately one field: a client that has just been handed a 503
// NOT_CONFIGURED needs to know which screen to show, not why.
type FirstRunStatusResponse struct {
	Configured bool `json:"configured"`
}

// HealthResponse is GET /system/health. Every configured backup set's freshness
// verdict, computed fresh on every call. Build and process facts are
// GET /system/version's, deliberately not restated here.
type HealthResponse struct {
	BackupSets  []BackupSetHealth `json:"backup_sets"`
	GeneratedAt string            `json:"generated_at"`
}

// HostKeyProbeRequest is POST /ssh/host-key-probe. Opens a real outbound connection, trusts
// nothing.
type HostKeyProbeRequest struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

// HostKeyProbeResponse is what the server actually saw. Presenting it to an operator for
// approval is the caller's job.
type HostKeyProbeResponse struct {
	Algorithm      string `json:"algorithm"`
	Fingerprint    string `json:"fingerprint"`
	KnownHostsLine string `json:"known_hosts_line"`
}

// ImportSSHKeyRequest is POST /ssh-keys. Sent once; the caller discards its own copy
// immediately.
type ImportSSHKeyRequest struct {
	Passphrase    string `json:"passphrase"`
	PrivateKeyPEM string `json:"private_key_pem"`
}

// ImportSSHKeyResponse is the reference a later create-backup-set call carries instead of
// key material.
type ImportSSHKeyResponse struct {
	Algorithm   string `json:"algorithm"`
	Fingerprint string `json:"fingerprint"`
	ID          string `json:"id"`
}

// ListActivityResponse is GET /activity, newest first.
type ListActivityResponse struct {
	Events []ActivityEvent `json:"events"`
}

// ListArtifactsResponse is GET /backups and GET /quarantine. An object with one array field,
// never a bare top-level array.
type ListArtifactsResponse struct {
	Artifacts []Artifact `json:"artifacts"`
}

// ListBackupSetsResponse is GET /backup-sets. An object with one array field, never a bare
// top-level array.
type ListBackupSetsResponse struct {
	BackupSets []BackupSet `json:"backup_sets"`
}

// ListOperationsResponse is GET /operations, newest first. The list counterpart of GET
// /operations/{id}, for a client that has no operation id to poll
// with.
type ListOperationsResponse struct {
	Operations []Operation `json:"operations"`
}

// ListStorageStatusResponse is GET /system/storage. The manager-wide reading a dashboard gauge is
// drawn from, plus one entry per configured backup set.
type ListStorageStatusResponse struct {
	BackupSets []StorageStatus `json:"backup_sets"`
	Manager    ManagerStorage  `json:"manager"`
}

// ListValidatorsResponse is GET /validators. Read-only by design: a client-extensible catalog
// would be an arbitrary-command surface.
type ListValidatorsResponse struct {
	Validators []Validator `json:"validators"`
}

// ManagerStorage is the one manager-wide storage reading: what the backup root's
// filesystem holds, what this manager itself accounts for, and which
// of the two the gauge is a fraction of. Distinct from the
// per-backup-set list beside it, which answers a different question
// and cannot answer this one: a fresh instance has no backup sets,
// two sets on one volume are two entries reporting the same disk,
// and the storage cap is one ceiling for the whole manager. When
// known is false every byte count is 0 and level is empty; render
// that as "capacity is not known yet", never as zero bytes and never
// as a percentage.
type ManagerStorage struct {
	AvailableBytes    uint64 `json:"available_bytes"`
	BindingConstraint string `json:"binding_constraint"`
	CapBytes          uint64 `json:"cap_bytes"`
	CatalogBytes      uint64 `json:"catalog_bytes"`
	CatalogBytesKnown bool   `json:"catalog_bytes_known"`
	CriticalFreeBytes uint64 `json:"critical_free_bytes"`
	Denominator       string `json:"denominator"`
	FreeBytes         uint64 `json:"free_bytes"`
	HeadroomBytes     uint64 `json:"headroom_bytes"`
	Known             bool   `json:"known"`
	Level             string `json:"level"`
	LimitBytes        uint64 `json:"limit_bytes"`
	MeasuredPath      string `json:"measured_path"`
	OtherBytes        uint64 `json:"other_bytes"`
	OtherBytesKnown   bool   `json:"other_bytes_known"`
	TotalBytes        uint64 `json:"total_bytes"`
	UnknownReason     string `json:"unknown_reason"`
	UsedBytes         uint64 `json:"used_bytes"`
	WarningFreeBytes  uint64 `json:"warning_free_bytes"`
}

// Operation is one durable operation record. Timestamp fields are omitted, not
// zero-valued, until the event they name has happened. progress is
// the separate, ephemeral thing: see OperationProgress for why it is
// a nested object that is simply absent rather than a set of fields
// on this record.
type Operation struct {
	Action         string             `json:"action,omitempty"`
	Actor          string             `json:"actor,omitempty"`
	BackupSetID    string             `json:"backup_set_id,omitempty"`
	ConfigRevision string             `json:"config_revision,omitempty"`
	CreatedAt      string             `json:"created_at,omitempty"`
	Error          string             `json:"error,omitempty"`
	FinishedAt     string             `json:"finished_at,omitempty"`
	OperationID    string             `json:"operation_id"`
	Progress       *OperationProgress `json:"progress,omitempty"`
	Result         string             `json:"result,omitempty"`
	StartedAt      string             `json:"started_at,omitempty"`
	Status         string             `json:"status"`
}

// OperationProgress is live progress for an operation that is running in THIS process
// right now (docs/EPIC-B-multi-nas.md §52). It is sampled from the
// transfer engine while a run cycle executes and is never written to
// the operations table: an operation record is durable and
// crash-safe, and progress is neither, so persisting it would put a
// tick-rate write path on the one record whose durability guarantees
// exist to avoid exactly that, and would resurrect a dead cycle's
// last reading after a restart as though it were live. So this field
// is present only while the cycle producing it is executing here. A
// finished operation, and one that was running before a restart,
// both carry no progress object at all, which is not the same answer
// as zero and must not be rendered as one. Nothing here is a
// percentage of the whole operation: a run cycle is a pass over
// every enabled backup set, and the artifacts it will find are not
// known when it starts, so no honest denominator for the whole
// exists. The byte counters describe the ONE artifact being copied
// at observed_at; the counters beside them say where in the cycle
// that artifact sits.
type OperationProgress struct {
	Artifact         string `json:"artifact,omitempty"`
	ArtifactsDone    int    `json:"artifacts_done"`
	BackupSetID      string `json:"backup_set_id,omitempty"`
	BackupSetsDone   int    `json:"backup_sets_done"`
	BackupSetsTotal  int    `json:"backup_sets_total"`
	BytesPerSecond   *int64 `json:"bytes_per_second,omitempty"`
	BytesTotal       *int64 `json:"bytes_total,omitempty"`
	BytesTransferred *int64 `json:"bytes_transferred,omitempty"`
	ObservedAt       string `json:"observed_at"`
	Sequence         int64  `json:"sequence"`
	Stage            string `json:"stage"`
}

// RetentionPlan is A server-computed retention plan. The client may only apply one by
// id; it never proposes what to delete.
type RetentionPlan struct {
	BackupSetID       string             `json:"backup_set_id"`
	ConfigRevision    string             `json:"config_revision"`
	DeleteCount       int                `json:"delete_count"`
	ExpiresAt         string             `json:"expires_at"`
	InventoryRevision string             `json:"inventory_revision"`
	KeepCount         int                `json:"keep_count"`
	OperationID       string             `json:"operation_id,omitempty"`
	PlanID            string             `json:"plan_id"`
	ReclaimBytes      int64              `json:"reclaim_bytes"`
	Verdicts          []RetentionVerdict `json:"verdicts"`
}

// RetentionSchema is the closed value sets and bounds a retention chain is validated
// against, served rather than transcribed into a frontend.
type RetentionSchema struct {
	DefaultTiers     []RetentionTier `json:"default_tiers"`
	Granularities    []string        `json:"granularities"`
	KeepMax          int             `json:"keep_max"`
	PeriodDaysMax    int             `json:"period_days_max"`
	ReservedTierName string          `json:"reserved_tier_name"`
	TierNamePattern  string          `json:"tier_name_pattern"`
	WindowUnits      []string        `json:"window_units"`
}

// RetentionSettings is the retention policy actually in effect. tiers is always the
// RESOLVED chain.
type RetentionSettings struct {
	ProtectLastKnownGood bool            `json:"protect_last_known_good"`
	Tiers                []RetentionTier `json:"tiers"`
	Timezone             string          `json:"timezone"`
	WeekStartsOn         string          `json:"week_starts_on"`
}

// RetentionTier is one link in the retention chain, on the wire. The same shape is
// read and written, so a client round-trips exactly what it was
// served.
type RetentionTier struct {
	Granularity string `json:"granularity"`
	Keep        int    `json:"keep"`
	Name        string `json:"name"`
	PeriodDays  int    `json:"period_days,omitempty"`
	WindowUnit  string `json:"window_unit,omitempty"`
}

// RetentionTierSelection is one tier's claim on an artifact, and which of the two placements
// made it. FR-18 places every artifact twice, once by the timestamp
// this manager discovered it and once by the producer's own
// timestamp on the remote object, and KEEP is the union. FR-8 treats
// the second as untrusted, so which pass selected a tier is a
// different fact with different consequences and travels with the
// tier rather than with the verdict: one artifact can be selected by
// DAILY through one placement and by MONTHLY through the other.
type RetentionTierSelection struct {
	SelectedBy string `json:"selected_by"`
	Tier       string `json:"tier"`
}

// RetentionVerdict is what the plan decided for one artifact, and why.
type RetentionVerdict struct {
	Action         string                   `json:"action"`
	Artifact       string                   `json:"artifact"`
	Reason         string                   `json:"reason"`
	TierSelections []RetentionTierSelection `json:"tier_selections,omitempty"`
	Tiers          []string                 `json:"tiers,omitempty"`
}

// RotatePasswordRequest is POST /auth/password. Requires an already-authenticated session AND
// the current password: holding a cookie is not enough.
type RotatePasswordRequest struct {
	CurrentPassword string `json:"currentPassword"`
	NewPassword     string `json:"newPassword"`
}

// RunningWork is what a run cycle is doing for one backup set right now (issue
// #350). It is the content of the warning shown before edit mode
// opens: discarding a partial transfer of a named artifact is a
// materially different cost from cancelling a scheduler tick that
// has not started work, and only a message saying which one it is
// lets an operator decide.
type RunningWork struct {
	Artifact string `json:"artifact"`
	Stage    string `json:"stage"`
}

// SessionResponse is GET /auth/session.
type SessionResponse struct {
	Username string `json:"username"`
}

// SetEnabledRequest is POST /backup-sets/{id}/enabled. A disabled backup set is excluded
// from every run cycle and nothing already backed up is touched,
// which is why this is state-changing but not destructive.
type SetEnabledRequest struct {
	Enabled bool `json:"enabled"`
}

// SetReadOnlyRequest is POST /backup-sets/{id}/read-only. Declares, or withdraws, a backup
// set's read-only status (issue #282). Turning it on only prevents a
// future deletion; turning it back off does not retroactively
// authorise deleting anything already retained under it, so this is
// state-changing but not destructive.
type SetReadOnlyRequest struct {
	ReadOnly bool `json:"read_only"`
}

// SettingsResponse is GET and PATCH /settings both return this: the settings now in
// effect plus the rules they were validated against.
type SettingsResponse struct {
	Capacity  CapacitySettings  `json:"capacity"`
	Retention RetentionSettings `json:"retention"`
	Schema    SettingsSchema    `json:"schema"`
}

// SettingsSchema is the schema half of the settings response.
type SettingsSchema struct {
	Retention RetentionSchema `json:"retention"`
}

// StorageStatus is one backup set's capacity assessment.
type StorageStatus struct {
	Available         bool   `json:"available"`
	AvailableBytes    uint64 `json:"available_bytes"`
	BackupSetID       string `json:"backup_set_id"`
	CriticalFreeBytes uint64 `json:"critical_free_bytes"`
	FreeBytes         uint64 `json:"free_bytes"`
	Level             string `json:"level"`
	LocalPath         string `json:"local_path"`
	TotalBytes        uint64 `json:"total_bytes"`
	UnavailableReason string `json:"unavailable_reason"`
	WarningFreeBytes  uint64 `json:"warning_free_bytes"`
}

// SubmitOperationRequest is POST /operations. The idempotency key is a header, not a body
// field: it is a property of the retry, not of the operation.
type SubmitOperationRequest struct {
	Action         string `json:"action"`
	ConfigRevision string `json:"config_revision"`
}

// TestConnectionRequest is POST /backup-sets/test-connection. A reachability and
// authentication check, in one of two modes: name backup_set_id to
// re-check a set that already exists, or supply the connection
// details to check a candidate before it is saved. Exactly one mode
// per request. A client testing a persisted set neither knows nor
// has to echo back that set's key reference and trusted host line,
// which is what keeps a read-only "does this still work" check from
// being able to test something else.
type TestConnectionRequest struct {
	BackupSetID    string `json:"backup_set_id"`
	Host           string `json:"host"`
	KnownHostsLine string `json:"known_hosts_line"`
	Port           int    `json:"port"`
	RemotePath     string `json:"remote_path"`
	SSHKeyID       string `json:"ssh_key_id"`
	User           string `json:"user"`
}

// TestConnectionResponse is the outcome of a pre-save connection test.
type TestConnectionResponse struct {
	Message string `json:"message,omitempty"`
	OK      bool   `json:"ok"`
}

// UpdateBackupSetRequest is PATCH /backup-sets/{source}/{set}. A SPARSE edit of one
// already-persisted backup set (issue #350): every property is
// optional, and a property this body omits is left exactly as it is
// rather than cleared. That is what lets the Web UI's per-box Save
// persist only the box it belongs to. It deliberately carries no
// name/source_name (a backup set's identity keys every journal row,
// artifact id and recovery manifest it has ever produced, so a
// rename is a migration rather than an edit) and no
// ssh_key_id/known_hosts_line (those are the results of the import
// and probe steps, and re-trusting a host is a trust decision rather
// than an edit).
type UpdateBackupSetRequest struct {
	CompletionStrategy *string   `json:"completion_strategy"`
	Host               *string   `json:"host"`
	Include            *[]string `json:"include"`
	LocalPath          *string   `json:"local_path"`
	Port               *int      `json:"port"`
	RemotePath         *string   `json:"remote_path"`
	StableForSeconds   *int      `json:"stable_for_seconds"`
	StaleAfterSeconds  *int      `json:"stale_after_seconds"`
	User               *string   `json:"user"`
	ValidatorID        *string   `json:"validator_id"`
}

// UpdateCapacitySettings is A PARTIAL capacity update. An omitted field is left exactly as the
// running configuration has it. An explicit 0 is a request, not an
// omission: on this block zero means "no cap" and "no warning line",
// which is why every field is nullable rather than a plain number.
type UpdateCapacitySettings struct {
	CapBytes          *int64 `json:"cap_bytes"`
	CriticalFreeBytes *int64 `json:"critical_free_bytes"`
	SafetyMarginBytes *int64 `json:"safety_margin_bytes"`
	WarningFreeBytes  *int64 `json:"warning_free_bytes"`
}

// UpdateRetentionSettings is A PARTIAL retention update. An omitted field is left exactly as
// the running configuration has it; omitting tiers leaves the chain,
// and a legacy file's own spelling of it, untouched.
type UpdateRetentionSettings struct {
	ProtectLastKnownGood *bool           `json:"protect_last_known_good"`
	Tiers                []RetentionTier `json:"tiers"`
	Timezone             *string         `json:"timezone"`
	WeekStartsOn         *string         `json:"week_starts_on"`
}

// UpdateSettingsRequest is PATCH /settings. An enumerated request type, never a configuration
// passthrough.
type UpdateSettingsRequest struct {
	Capacity  *UpdateCapacitySettings  `json:"capacity"`
	Retention *UpdateRetentionSettings `json:"retention"`
}

// Validator is one registered application validator. An id and a sentence, and
// deliberately nothing else: the script it resolves to is
// server-side and a client never learns it.
type Validator struct {
	ID      string `json:"id"`
	Summary string `json:"summary"`
}

// VersionResponse is GET /system/version. Nothing here names an implementation: no
// rclone, no SQLite, no filesystem path.
type VersionResponse struct {
	APIVersion     string `json:"api_version"`
	Commit         string `json:"commit"`
	ConfigRevision string `json:"config_revision"`
	Configured     bool   `json:"configured"`
	CoreVersion    string `json:"core_version"`
	EngineVersion  string `json:"engine_version"`
	GoVersion      string `json:"go_version"`
	Ready          bool   `json:"ready"`
}

// SchemaTypes maps a contract schema name to a zero value of the generated
// Go type for it. A conformance test reaches a type by contract name
// through this map rather than through a hand-written lookup, so a schema
// added to the contract cannot quietly go unchecked.
var SchemaTypes = map[string]any{
	"ActivityEvent":               ActivityEvent{},
	"ApplyRetentionRequest":       ApplyRetentionRequest{},
	"Artifact":                    Artifact{},
	"ArtifactCheckResponse":       ArtifactCheckResponse{},
	"ArtifactReinstateResponse":   ArtifactReinstateResponse{},
	"AuthErrorResponse":           AuthErrorResponse{},
	"BackupSet":                   BackupSet{},
	"BackupSetEditHold":           BackupSetEditHold{},
	"BackupSetEditHoldState":      BackupSetEditHoldState{},
	"BackupSetHealth":             BackupSetHealth{},
	"BackupSetSpec":               BackupSetSpec{},
	"CapabilitiesResponse":        CapabilitiesResponse{},
	"CapacitySettings":            CapacitySettings{},
	"CatalogFailure":              CatalogFailure{},
	"CatalogReportResponse":       CatalogReportResponse{},
	"CompleteFirstRunResponse":    CompleteFirstRunResponse{},
	"ConfigRevisionStaleResponse": ConfigRevisionStaleResponse{},
	"CreateBackupSetRequest":      CreateBackupSetRequest{},
	"CreateBackupSetResponse":     CreateBackupSetResponse{},
	"CredentialsRequest":          CredentialsRequest{},
	"ErrorBody":                   ErrorBody{},
	"ErrorResponse":               ErrorResponse{},
	"FirstRunStatusResponse":      FirstRunStatusResponse{},
	"HealthResponse":              HealthResponse{},
	"HostKeyProbeRequest":         HostKeyProbeRequest{},
	"HostKeyProbeResponse":        HostKeyProbeResponse{},
	"ImportSSHKeyRequest":         ImportSSHKeyRequest{},
	"ImportSSHKeyResponse":        ImportSSHKeyResponse{},
	"ListActivityResponse":        ListActivityResponse{},
	"ListArtifactsResponse":       ListArtifactsResponse{},
	"ListBackupSetsResponse":      ListBackupSetsResponse{},
	"ListOperationsResponse":      ListOperationsResponse{},
	"ListStorageStatusResponse":   ListStorageStatusResponse{},
	"ListValidatorsResponse":      ListValidatorsResponse{},
	"ManagerStorage":              ManagerStorage{},
	"Operation":                   Operation{},
	"OperationProgress":           OperationProgress{},
	"RetentionPlan":               RetentionPlan{},
	"RetentionSchema":             RetentionSchema{},
	"RetentionSettings":           RetentionSettings{},
	"RetentionTier":               RetentionTier{},
	"RetentionTierSelection":      RetentionTierSelection{},
	"RetentionVerdict":            RetentionVerdict{},
	"RotatePasswordRequest":       RotatePasswordRequest{},
	"RunningWork":                 RunningWork{},
	"SessionResponse":             SessionResponse{},
	"SetEnabledRequest":           SetEnabledRequest{},
	"SetReadOnlyRequest":          SetReadOnlyRequest{},
	"SettingsResponse":            SettingsResponse{},
	"SettingsSchema":              SettingsSchema{},
	"StorageStatus":               StorageStatus{},
	"SubmitOperationRequest":      SubmitOperationRequest{},
	"TestConnectionRequest":       TestConnectionRequest{},
	"TestConnectionResponse":      TestConnectionResponse{},
	"UpdateBackupSetRequest":      UpdateBackupSetRequest{},
	"UpdateCapacitySettings":      UpdateCapacitySettings{},
	"UpdateRetentionSettings":     UpdateRetentionSettings{},
	"UpdateSettingsRequest":       UpdateSettingsRequest{},
	"Validator":                   Validator{},
	"VersionResponse":             VersionResponse{},
}
